= Linux
== Komutlar

=== Komut Kullanım Şablonu
komut [paremetreler] +
ls [-l,-h,-p] +
ls

=== `pwd` Komutu
Konsolda bulunduğumuz klasörün tam yolunu konsola yazdırır. İngilizce, _print working directory_ 
cümlesinin kısaltmasıdır.

=== `cd` Komutu
Konsolda, başka bir klasöre geçmemizi sağlar. Kullanımı `cd /gecilecek/klasör` şeklindedir.

[source,bash]
----
[root@archlinux ~]# pwd
[root@archlinux ~]# /root
[root@archlinux ~]# cd /etc/conf.d
[root@archlinux conf.d]# pwd
[root@archlinux conf.d]# /etc/conf.d
----
`cd ~` komutu ile aktif kullanıcının ana klasörüne geçilir. +
`cd ..` ile bulunduğunuz klasörün bir üst klasörüne geçersiniz. +
`cd -` ile bir önce bulunduğunuz klasöre geçersiniz.

=== `ls` Komutu
Bir klasör içerisindeki dosyaları ve klasörleri listelemek için kullanılır. `ls` komutunun 
kullanım formatı şu şekildedir:
[source,bash]
ls [paremetreler] [listelenecek_klasör1 listelenecek_klasör2 ...]

`ls` komutu, konsolda bulunduğunuz klasörü listeler. +
`ls /etc/httpd` komutu, `/etc/httpd` klasörü içerisindeki dosyaları ve klasörleri listeler. +
`ls /etc/httpd /var` komutu, hem `/etc/httpd` klasörünü hem de `/var` klasörünü listeler.

==== `ls` Komutunun Önemli Paremetreleri
===== `-a` Parametresi
Gizli dosyalar ve klasörler de dahil olacak şekilde, klasör içerisindeki tüm(_all_) dosyaları listeler.

===== `-l` Parametresi
Dosyaları ve klasörleri sütunlar halinde ve ayrıntılı olarak listeler.

===== `-h` Parametresi
Ayrıntılı listelemede, dosya ve klasör boyutlarını okunaklı(_human readable_) olarak yazar. `-l` parametresi
ile beraber kullanılır. Dosya boyutlarını, büyüklüğüne göre uygun biçimde KiloByte, MegaByte ve GigaByte birimlerine çevirir. 
KiloByte için *K*, MegaByte için *M* ve GigaByte için *G* kısaltmasını kullanır.
// 20.10.2017 GBIL207 Dersi Sonu

===== `-R` Parametresi
Bu parametre ile iç içe olan tüm klasörler ve dosyalar listelenir.

===== `-S` Parametresi
Dosya ve klasörleri, önce boyutu büyük olan gelecek şekilde boyutuna göre sıralar.

===== `-r` Parametresi
Dosya ve klasörleri, geçerli olan sıralamanının tersi yönünde sıralar.

===== `-t` Parametresi
Yeni düzenlenen dosya ve klasörler önce gelecek şekilde, doya ve klasörleri değiştirilme tarihine göre listeler.

===== `-X` Parametresi
Dosya ve klasörleri uzantısına göre alfabetik olarak sıralar.

=== `touch` Komutu
`touch` komutu bir dosyanın, oluşturulma ve değiştirilme tarihini, komutun verildiği an olarak ayarlar.
Eğer dosya mevcut değilse yeni bir dosya oluşturur.

=== `mkdir` Komutu
Klasör oluşturmak için kullanılan komuttur. Kullanım şekli aşağıdaki gibidir. +
`mkdir [seçenekler]... klasör...`

==== `mkdir` Komutunun Parametreleri
===== `-p` Parametresi
`mkdir` komutu `-p` parametresi ile birlikte kullanıldığında, oluşturulacak klasör eğer üst klasörler de 
barındırıyorsa, komut bu klasörleri de oluşturur.

.Örnekler
[source, bash]
----
mkdir yeni
# Bulunduğunuz klasörün içinde yeni isimli bir klasör oluşturur.

mkdir bir/iki
# Eğer bulunduğunuz klasörde bir klasörü varsa bir klasörü içinde iki isimli klasör oluşturur.

mkdir /iki/uc
# Bulunduğunuz klasörde iki isimli klasör yoksa, bu komut hata verecektir.

mkdir /iki/uc
# Bulunduğunuz klasörde iki isimli klasör yoksa, bu komut hata verecektir.

mkdir -p /iki/uc
# Bulunduğunuz klasörde iki isimli klasör yoksa oluşturulur. Daha sonra bu klasör içinde uc klasörü oluşturulur.
----
=== `cp` Komutu
Dosya ve klasörleri kopyalamak için kullanılan komuttur. Kullanım şekli aşağıdaki gibidir. +
`cp [seçenek]... kaynak_dosya hedef_dosya` +
`cp [seçenek]... kaynak_dosya... hedef_klasör`
//25.10.2017 BIL207 Dersi Sonu

.Örnekler
[source, bash]
----
cp dosya.txt deneme/
# Bulunduğunuz klasördeki dosya.txt dosyasını, yine bulunduğunuz klasörde yer alan klasör deneme klsörü içine kopyalar.

cp dosya.txt deneme/dosya_kopyasi.txt
# Bulunduğunuz klasördeki dosya.txt dosyasını, yine bulunduğunuz klasörde yer alan klasör deneme klsörü içine kopyalar.

cp dosya1.txt dosya2.txt dosya3.txt dosya4.txt deneme/
# Bulunduğunuz klasörde bulunan dosya1.txt dosya2.txt dosya3.txt dosya4.txt dosyalarını deneme klasörü içine kopyalar.

cp dosya.txt dosya.txt.bak
# Bulunduğunuz klasördeki dosya.txt dosyasını, aynı klasörde dosya.txt.bak olarak kopyalar.

cp klasor1/ klasor2/
# cp komutu ek seçenekler olamadan klasör kopyalama eylemini gerçekleştiremez. Bu komut hata verecektir.

cp -r klasor1/ klasor2/
# Bulunduğunuz klasörde klasor2 klasörü mevcut değilse, bulunduğunuz klasörde içeriği klasor1 ile aynı olan klasor2 isimli bir klasör oluşturur.
# Eğer bulunduğunuz klasörde klasor2 isimli bir klasör varsa, klasor1 klasörünü klasor2 içine kopyalar.
----

=== `mv` Komutu
Dosya ve klasörleri taşımak için kullanılan komuttur. Ayrıca bu komut, aynı klasör içerisinde bir dosya veya klasör taşıma yöntemi ile 
bir soya va klasörü yeniden adlandırmak için de kullanılabilir. Kullanım şekilleri aşağıda verilmiştir.

`mv [seçenek]... kaynak_dosya hedef_dosya` +
`mv [secenek]... kaynak... hedef_klasor`

.Örnekler
[source, bash]
----
mv abc.txt def.txt
# Çalıştığınız klasörde bulunan abc.txt dosyasını def.txt dosyasına taşır

mv def.txt Yeni/
# Çalıştığınız klasörde def.txt dosyasını, yine çalıştığınız klasörde bulunan Yeni/ klasörü için taşır.

mv dosya1 dosya2 dosya3 /home/okten/son/
# Çalıştığınız klasörde bulunan dosya1, dosya2, dosya3 dosyalarını /home/okten/son/ klasörüne taşır.
----

=== `rm` Komutu
Dosya veya klasörleri silmek için kullanılan komuttur. Kullanımı şağıdaki gibidir.

`rm [seçenek]... [dosya]...`

.Örnekler
[source, bash]
----
rm dosya1
# Çalıştığınız klasörde bulunan dosya1 dosyasını siler.

# Bir klasör içindekilerle beraber silinmek isteniyorsa rm komutu aşağıdaki gibi kullanılır.
rm -rf Klasor/

# rm komutu ile aşağıdaki gibi çalıştırmanız sisteminiz için tehlike arz eder.
rm -rf /
----

|===
|İfade |Anlamo

|.
|Yeni satır karakteri dışında herhangi bir karakter

|\w
|Bir Kelime

|\d
| Bir rakam

|\s
| Bir boşluk karakteri

|[abc]
| a, b veya c karakterlerinden herhangi biri

|[^abc]
| a, b veya c karakterleri haricinde bir karakter

|[a-z]
|a ile z arasında karakterlerden herhangi biri

|[0-9]
|0 ile 9 arasında karakterlerden herhangi biri

|[B-K]
|B ile K arasında karakterlerden herhangi biri

|^
| Satır veya string başı

|$
| Satır veya string sonu



|
|===

açık katnak
