= Adobe Flash CS6

== Flash Nedir?
Bir çok göz alıcı web sitesinde, çevrimiçi sosyal oyunlarda ve hatta reklam bannerlarında gördüğümüz 
animasyonların büyük çoğunluğu Flash ile oluşturulmuştur. Ama Flash günümüzde sadece animasyon oluşturmaktan 
daha fazlasını da yapmaktadır. Adobe Flash CS6 ile video ve ses doyalarını düzenleyebilir hatta web tabanlı
uygulamalar geliştirmek için bir veritabanına bile bağlanabilirsiniz.

Flash CS6 dört temel özelliğe sahiptir.

**Çizim Ortamı : ** Flash, kompleks çizimleri ve tipografileri işlemek için son derece yeterli araçlar 
bütününe sahiptir. Kuzeni Adobe Illustrator CS6 gibi Flash'ında asli işlerinden biri detaylı, zengin ve 
ölçeklenebilir dijital çizimler oluşturmaktır.Flash, *.ai* (Illustrator) ve *.psd* (Photoshop) 
dosyalarını doğrudan destekler.

**Animasyon :** Flash, resim, ses ve videolar içeren ve web üzerinden hızlı bir şeklilde yüklenebilen sade 
animasyonlar oluşturur. Flash animasyonlar web sitelerinde ve sosyal ağlarda gösterilebilir. Ayrıca, interaktif 
web tabanlı reklam panoları için ilk akla gelen geliştieme ortamıdır.

Flash, geleneksel olarak kullanılan *frame-by-frame* animasyon methodunun yası sıra, *tweening* 
adı verilen bir başka animasyon metodunu da kullanır. Tweening metodu, anime edilecek bir nesnenin ik ve son
durumları belirlendikten sonra bu iki durum arasındaki hareketin bilgisayar tarafından doldurulması anlamın gelmektedir.

**Yerleşim Planı : ** Flash sahnesi size sıradışı web arayüzleri oluşturmak için esnek bir ortam sunar. İçeriğinizi 
Flash sahnesinin herhangi bir yerine özgür ve kesin bir şekilde konumlandırabilir ve böylece arayüzünüzü web sayfasının 
sınırlarını kırarak daha da öne çıkartabilirsiniz. Ayrıca Flash bir çok eğlenceli tipografiler ve sıra dışı yazı tiplerini 
içinde barındırır.

**Programlama : ** Flash CS6'nın az farkedilmesine rağmen en güzel özelliklerinden biri yeteneklerinizi 
basit ve tasarım ve animasyonların daha da ötesine taşıyan, güçlü bir yerleşik betik dili olan __AcitionScript__'dir.

== Flash Player
Flash animasyonlarını oynatmak için kullanılan bir uygulamadır. Flash player, bir çok moderm tarayıyıya uzantı olarak 
eklenebilir. Flash animasyonları *.swf* uzantısına sahiptir. +
Flash Player sadece bir video oynatıcısı değildir. Tıklama ve fare hareketlerine göre tepkiler verip dinamik içerik sunumu yapabilir.
Örneği Flash ile tek bir karakteri olan basit bir oyun yapılabilir. Klavyeden ok tuşları yardımıyla bu karakter hareket ettirilebilir.


== Flash Dosya Türleri
Flash'da *.fla*, *.xfl*, *.swf* ve *.html* olmak üzere dört adet dosya türü kullanılır. *.fla* Flash'ın proje dosya biçimidir. 
Proje dosyalarında; resim, ses ve video gibi kaynkları oluşturabilir ve düzenleyebilirsiniz. *.fla* dosyalarını web tarayıcıları tanımazlar. 
Projeniz tamamlandığında *.fla* dosyasını kullanarak, projenizin ürünü olan *.swf* dosyası oluşturulur.
== Flash'da Çizim Yapma
Flash'da çizimler _Merge Drawing Mode_ ve _Object Drawing Mode_ olmak üzere iki modda yapılabilir. 

=== Merge Drawing Mode Kullanma
Flash'da varsayılan mod Merge Drawing Mode'dur. Bu modda şekiller bir çamur gibidir. Kolayca parçalanabilirler.
Mesela, bu modda çizilen bir dairenin içi ve çevresi ayrı ayrı seçilebilir. Ayrıca bu modda çizilen iki nesne 
üst üsteyken, seçili nesneye çift tıklanırsa bu iki nesne kaynaşır yani bir bütün haline gelir.

Object Drawing nesnesini geçici olarak Merge Drawing modda düzenlenmek istenilirse, o nesnenin üstüne çift tıklanır. 
Bu durumda _Drawing Object_ sahnesi açılır ve gerekli düzenlemeler Merge Drawing modda yapılarak ana sahneye geri dönülür. 
Son durumda, ana sahnemizde bu nesne yine _Object Drawing_ nesnesi olarak klacaktır. +
Object Drawing nesnesi kalıcı olarak Merged Drawing nesnesin dönüştürülmek istenilirse `Modify` menüsünden `Break Apart`
seçilir. Bu durumda şekil artık _Merge Drawing_ nesnesi olacaktır. + 
Merged Drawing nesnesini çerçevesinin uçları, eğer _Snap to object_ aktif ise otomatik olarak birlerşir.

=== Semboller
Sembol, Flash’ta bir kez oluşturduktan sonra belgenizde veya diğer
belgelerde tekrar tekrar kullanabildiğiniz grafikler, düğmeler ve movie clip’ler
için kullanılan bir terimdir. Semboller birçok animasyonda dosya boyutunu
küçültebilir ve yükleme süresini kısaltabilir. Belirli bir sembolü bir projede
sayısız kez kullanabilirsiniz, fakat Flash’a bu sembolle ilgili veriler bir kez dahil
edilir. +
Semboller Kitaplık panelinde saklanır. Bir sembolü sahne’nin üzerine
sürüklediğinizde, Flash orijinal sembolü kitaplıkta bırakarak sembolün bir
örneğini oluşturur. Örnek, bir sembolün sahne’ye yerleştirilen veya başka bir
sembol içinde yuvalanan bir kopyasıdır.
Flash’ta üç tip sembol vardır ve bunların her biri kendine özgü avantajlara ve
kısıtlamalara sahiptir. Kitaplık panelinde bir sembolün yanındaki simgeye
bakarak bunun bir grafik mi düğme mi yoksa Film klibi mi olduğunu
anlayabilirsiniz. Flash'da yer alan sembol türleri şunlardır:

* Film Klibi Sembolleri
* Düğme Sembolleri
* Grafik Sembolleri




[bibliography]
== Referanslar
- _Sembollerle Çalışma_, *Meryem AKSU*, https://meryemaksu.weebly.com/sembollerle-ccedilal305351ma.html
