= İçerik Yönetim Sistemi

== Temel Kavramlar

=== İçerik
Editöryal süreçlerden geçmiş ve yayınlanarak insanlar tarafından
tüketilen verilerdir.

=== İçerik Yönetim Sistemi
İçeriği etkin bir şekilde yönetmek için gereken çeşitli otomasyon
görevlerine sahip olan yazılımlardır.
İçerik Yönetim sistemi(Content Management System) CMS

CMS genellikle, depoda saklanan içerik ile etkileşime
giren çok-kullanıcılı ve sunucu tabanlı bir yazılımdır.

CMS içeriğin, içeriği tüketecek kullanıcılara hazır hale
gelebilmesi için gerekli olan yeni içerik üretme, var olan
içeriği düzenleme gibi editöryal süreçler için bir
editör kullanmaya izin verir.

=== İçerik Yönetime Sistemi Türleri
* Web Content Management(WCM) Yönetimi yapılacak içerikler bir
web sitesi aracılığıyla sunulur.
* Enterprise Content Management(ECM): Büyük şirketler tarafından
genelde dökümanları düzenli tutumak için kullanılan CMS dir.
* Digital Asset Management(DAM): Resim, müzik ve video gibi zengin
içeriğe sahip kaynakların yönetimi için kullanılan sistemlerdir.
* Records Managemet : İş süreçleri tarafından oluşturulan alım
satım işlemlerinin bilgilerin yönetimini yapan sistemlerdir.






== İçerik Yönetim Sistemlerinin Faydaları

=== İçerik Kontrolü
İçerik büyüdükçe oluşan karmaşayı ortadan kaldırmak için içerikler üzerinde size kontrol mekanizması sunar.
CMS bir içeriğin tüm izlerini kayıt altında tutar. Örneğini; içeriğin nerede saklandığı, içeriğin kim tarafından ve 
hangi tarihte oluşturulduğu, içeriğe kimler tarafında erişim yapıldığı, içeriğin başka içeriklerle olan ilişkileri 
gibi bilgilerin hepsi CMS tarafından bilinir. Böylelikle CMS, içeriğimizin başına gelecek kötü durumlara engel olmuş olur.

CMS aşağıdaki temel yönetim fonksiyonlarına sahiptir:

* _**İzinler**_ : İçeriği kimlerin okuyacağı, içeriği kimlerin düzenleyebileceği veya içeriği kimlerin silebileceği.
* _**Durum Yönetimi ve Akış**_ : İçerik yayınlandı mı?, içerik taslak olarak mı kaydedildi?, içerik arşive mi çekildi?
* _**Versiyonlama**_ : İçerik kaç defa değişti?, İçerik bir ay önce nasıldı?, İçeriğin en son hali ile önceki halleri arasında 
ne gibi farklar var?
* _**Bağımlılık Yönetimi**_ : İçerilk hangi başka içeriklerle birlikte kullanılıyor?, Eğer bu içeriği silersem başka içerikler 
bundan etkilenir mi?i, Hangi içerikler kullanılmıyor veya eksik referansa sahip. 
* _**Arama ve Organizasyon**_ : Belirli bir içerik parçasını nasıl içerikler içerisinde arayabilirim? Bir içeriğini kullanan tüm içerikleri 
nasıl bulabilirim?, İçerikler daha iyi organize etmek için nasıl gruplara ayırıp kategorilendirebilirim?

=== İçeriğin Yeniden Kullanılabilmesi
Bazı içeriklerin birden fazla yerde kullanılması veya birden fazla yolla kullanılması onun değerini arttırır.
Örneğin;

* Bir gazete web sitesi için bir haber makalesi düşünelim. Bu haber makalesi kendi sayfasında yer alır. Ayrıca "Flaş Haberler" içeriğinde 
yer alabilir. Ek olarak da, başka bir içerik için "İlişkili Haberler" bölümünde yer alabilir.
* Bir yazara ait kısa özgeçmiş, yazarın tüm yazılarının altında gözükebilir.
* Güvenlik Bildirim sözleşmesi, web sitesindeki tüm sayfaların altında gözükebilir.

Yukarıdaki durumlarda ortak olan içerik, bulunduğu her konumda tekrardan oluşturulmaz. Onun yerine, ortak içerik tek bir konuma sahiptir ve herhangi bir 
içerik tarafından kullanılacağı zaman bu konumdan çekilir. Böylece ortak içerik, bulunduğu her içerik için ayrı ayrı oluşturulmamış olacaktır.

Mesela, sitenizin her bir sayfasının altında, şirketinizin açık adresinin yer aldığını varsayalım. Eğer her bir sayfa için şirket adresi ayrı ayrı oluşturulmuş 
olsaydı, şirketinizin adresinin değişmesi durumunda tüm sayfaları tekrar düzenlemeniz gerekecekti. Ama şirket adresi içeriğini oluşturup diğer sayfalarda yeniden
kullandığınızda, şirket adresi içeriğinde yapılan değişiklik otomatik olarak bu içeriğin bulunduğu tüm sayfaları da etkileyecektir.

=== İçerik Otomasyonu ve Montajı
Tüm içeriğimiz tek bir kaynakta yer aldığından, içeriği sorgulama ve değiştirme işlemlerini muazzam bir şekilde gerçekleştiren bir sisteme sahip oluruz. 
Bu sistem sayesinde mesela, geçen ay oluşturulan makaleleri bulabilir veya içinde "karnıbhar" sözcüğü geçen tüm makaleleri listeleyebiliriz. 
Eğer içeriklerimiz düzgün bir yapıya sahip olursa, bu içeriklerin farklı koşullarda farklı görüntelenmesini sağlayabilirifarklı görüntelenmesini sağlayabilirizz
Örneğin;

* İçeriği farklı şekillerde yayınlanacak şekilde oluşturabilirsiniz.
* Otomatik olarak liste öğeleri ve gezinti menüleri oluşturabilirsiniz.
* Kullanıcıların yereline göre, içeri farklı dillerde gözükecek şekilde oluşturabilirsiniz.

=== İçerik Düzenleme İşlemini Kuvvetlendirir
İçerik üzerindeki hataların tespiti ve düzeltilmesi için CMS'ler gerekli araçlara sahiptir.

== İçerik Yönetim Sistemlerinin Yapamadıkları
=== İçerik Üretmek
İçerik yönetim sistemleri içerik oluşturamazlar. İçeriği oluşturmak ve organize etmek için güçlü bir zemin oluştururlar.

=== Pazar Araştırması
İçeriğiniz düzgün ve iyi yapılandırılmış bile olsa bu içeriğinizin farkedilmesini sağlamaz.

== Wordpress'i Kurmak
Wordpress'i kullanmaya başlamadan önce altyapısını oluşturmak gerekir. Bu ise 
Wordpress'i indirip kurmakdan daha fazlası demektir. İlk olarak bir alan adına 
ve web barındırma hizmetine ihtiyacımız olacak. 
Wordpress'i kullanmak için, Wordpress.com'da bir hesap alabilir ya da 
daha karışık olan yöntemi seçip Wordpress'i bir web barındırma alanına kurabilirsiniz. 

=== Alan Adı Alma
Wordpress'i kurup kullanmak için ilk adım bir alan adı edinmektir. _Alan adları_, bir websitesini 
ziyaret etmek için web tarayıcısının adres çubuğuna yazdığınız _eşsiz_ isimlerdir. +
Alan adlarının _eşsiz_ olması, aynı alan adının iki farklı web sitesi tarafından kullanılamayacağı 
anlmaına gelmektedir.

==== Alan Adı Uzantılarını Anlama
Alan adı alırken, alan adlarının sonundaki uzantılara önem vermek gerekir. Alan adlarının 
sonunda gördüğümüz, __.edu, .com, .biz, .net__ gibi uzantılara **üst-seviye alan adı uzantıları** 
denir. Alan adınız mutlaka bir üst-seviye alan adı uzantısı bulundurmak zorundadır. +
İki veya daha fazla alan adınıb birbirlerinden tek farkı üst-seviye alan adı uzantısı olabilir. 
Bu durumda bütün bu alan adları tek bir şahıs veya şirkete ait olmayabilir. Örneğin, 
`superbirblog.com` alan adını siz aldıysanız, `superbirblog.net` alan adı bir başkası tarafından alınmış olabilir.

[TIP]
.Alan Adlarına Sahip mi Oluruz Yoksa Kiralar mıyız?
====
Bir alan adı almak demek aslında onu belli bir süreliğine kiralamak anlamına gelir. Bir 
alan adını bir seneden on seneye kadar kiralayabilirsiniz. Fakat kiralama süresi dolmadan 
önce alan adını yeniden satın alıp belli süreliğine kiralamazsanız o alan adını kaybetmiş 
olursunuz. Alan adı serbest kalır ve bir başkası tarafından kiralanabilir.
====
Eğer bu sizin için bir problem teşkil ediyorsa, sadece üt-seviye alan adı uzantısı farklı olan 
birden fazla alan adını alabilirsiniz.

==== Alan Adlarının Maliyeti
Alan adı kiralamanın maliyeti, hizmet aldığınız yere ve hizmetinizin özelliklerine göre 3 dolardan 
300 dolara kadar çıkabilir. 

= awardspace.com
=== Okuma Ayarları

* Ana Sayfa Görüntülenmesi : Sitemizin web adresini yazdığımızda karşımıza çıkan sayfa olan 
ana sayfanın seçimini yapar. En son yazılarınız seçeneği seçildiğinde ana sayfada son makaleler
gözükür. Sabit sayfa seçildiğinde, Hakkında, İletişim gibi sabit sayfalardan birini ana sayfa 
olarak belirlemiş oluruz.

=== Tartışma Ayarları
* **Yazıda bağlantı verilen blogları haberdar etmeyi dene : ** +
Bu sçenek seçildiğinde, bloğunuzda oluşturduğunuz bir girdi eğer bir başka bloğa bağlantı içeriyorsa 
ilgili bloğa bi bildirim(trackback) yollanır.
* **Diğer bloglardan yeni makaleler için bağlantı bildirimlerini (geri bildirimler ve geri izlemeler) etkinleştir** : +
Bu seçenek seçildiğinde, diğer bloglardan size yollanan trackbak bildirimleri kabul edilir. Bir girdinizle ilgili alınan 
trackbak, o giridinin yorumlar kısmına otomatik olarak eklenir.
* **Yeni yazılar üzerine yorum yapılmasına izin ver :** +
Oluşturduğuuz girdilere yorum yapılmasına izin verir.
* **Yorumu yazan isim ve e-posta adresini doldurmak zorunda : ** +
İsim ve eposta bilgileri olmadan yorum yazılamayacağını belirtir. Bu özellik spam(istenmeyen) yorumları
engellemek için kullanılabilir.
* **Kullanıcılar yorum yapmak için kayıt olmalı ve giriş yapmalılar : **
Ancak kayıtlı kullanıcılar giriş yaptıkları durumda bir girdiye yorum yazabilirler. 
Kayıtsız kullanıcılar yorumyapamazlar.

== İçeriğinize Resim Ekleme
Yönetim panelinden `Yazılar -> Yeni Ekle` menü yolu izlenerek `Ortam Ekle` düğmesine basılır.


https://worldnetbilisim.com/cms-icerik-yonetim-sistemi-nedir-ne-ise-yarar/

https://docs.google.com/document/d/1mVyPn2oQXbfclHsM0J8lFKfFrkBv5e2i0rCijCWZJ0s/edit?usp=sharing
