:numbered:
:toc:
:example-caption: Alıştırma
= Hello, AsciiDoc!
Doc Writer <doc@example.com>

== Metin İşlemleri
PHP, string türünden değişkenler üzerinde işlem yapan birçok 
fonksiyona sahiptir.

**String Doğrulama
Srting doğrulama, bir string türünden değişkenin veya sabitin 
belli koşulları sağlayıp sağlamadığını kontrol etmektir.

*trim() Fonksiyonu : String türünden bir değişken veya sabitin
basşında ve sonunda bulunan 
beyaz karakterleri(boşluk, tab, yeni satır) siler. trim İngilizce 
budamak anlamına gelir.

$_POST değişkeni PHP'nin özel değşkenidir. 
Bu değişkenler PHP'de yerleşik bulunur ve temel 
eylemler için genel bilgiler saklar.
Bütün özel değişkenler $ işaretini takip eden
bir _ karakteri ve _ karakterinden sonra büyük
hafli bir değişken ismin sahiptirler.

*var_dump() Fonksiyonu : Bir değişkenin; değişken türü, içerik gibi 
ayrıntılarını gösterir. Genellikle dizi türünden değişkenlerin 
ayrıntılı incelenmesi için kullanılır.

*strlen() Fonksiyonu : string türünden bir değişkenin karakter uzunluğunu
döndürürü. Karakter uzunluğu hesaplanırken bütün 
karakterler(boşluk ve özel karakterler gibi) sayıya dahil edilir.
=== printf değişken belirtecinin yapısı
 Değişken temsilcisi % işareti ile başlar. Yapısı
	%idhunb
şeklindedir. 
Burada i, sayısal türlerin işaret gösteriminin nasıl yapılacağını
belirtir. - veya + değerleri alabilir.
- değer alması durumunda, negatif sayıların işareti gösterilir, 
pozitif sayıların işareti gösterilmez.
+ değer alması durumunda, egatif sayıların işareti gösterilir, 
pozitif sayıların işareti de gösterilir. Varsayılan değer - dir.

d, boşluk karakteri olarak işlev görür. Eğer değişkenin uzunluğu, 
toplam uzunluktan kısaysa, boşta kalan alan bu karakter ile doldurulur. 
Varsayılan değer boşluk karakteridir. Eğer 0 haricinde bir karakter 
atanmak istenirse başına ' karakteri konulur.

h hizalama belirtecidir. Eğer değişkenin uzunluğu, toplam uzunluktan kısaysa, 
değişken varsayılan olarak sağa hizalanır. Sağa hizalama için -, sola 
hizalama için + karakteri kullanılır. 

u, ilgili değişkenin yerleştirileceği alanın toplam karakter uzunluğunu belirler.

n, kayan noktalı sayılarda, . karakterinden sonra kaç basamak geleceğini belirler. 
.3  .5   .2   şeklinde ifade edilir. 

b, ilgili değişkenin hangi değişken türü dikkate alınarak yerleştirileceğini belirler.

%d Onluk Sayı sisteminde bir sayılarda
%f Kayan noktalı sayılarda
%s string


=== `strtolower` ve `strtoupper` Fonksiyonları
Metin türünden ifadeleri, küçük harflerden büyük harflere veya büyük harflerden küçük harflere 
çevirmek için kullanılırlar. Bir metinde bulunan küçük harfleri, büyük harflere çevirmek için 
`strtoupper` fonksiyonu, büyük harfleri küçük harflere çevirmek için `strtolower` fonksiyonu kullanılır.
`strtolower` ve `strtoupper` fonksiyonları Türkçe karakterlerin çevriminde yetersiz kalmaktadır. 
Türkçe karakterler büyük-küçük harf dönüşümü için, UTF-8 karakter kodlaması ve `mb_strtolower`, 
`mb_strtoupper` fonksiyonları kullanılabilir.

=== `ucwords` Fonksiyonu
Bir cümlenin her kelimesinin baş harfinin büyük harf yapmak için kullanılan fonksiyondur.
Örneğin,

[source,php]
$baslik = "amasyanın turistik yerleri";
echo ucwords($baslik); // Amasyanın Turistik Yerleri

Türkçe karakterler için bu işlem yapılmak istenirse `mb_convert_case` 
fonksiyonu kullanılmalıdır. Örneğin,

[source,php]
$baslik = "çalışma şartları";
echo mb_convert_case($baslik, MB_CASE_TITLE, "UTF-8"); // Çalışma Şartları

`mb_convert_case` fonksiyonu, `mb_strtoupper` ve `mb_strtolower` fonksiyonlarının işlevlerini de yerine getirir.
Örneğin,

[source,php]
$baslik = "çalışma şartları";
echo mb_convert_case($baslik, MB_CASE_UPPER, "UTF-8"); // ÇALIŞMA ŞARTLARI

[source,php]
$baslik = "çalışma şartları";
echo mb_convert_case($baslik, MB_CASE_LOWER, "UTF-8"); // çalışma şartları

=== `substr` Fonksiyonu
Metin türünden bir ifadenin bir parçasını almak için kullanılan fonksiyondur.

PHP'de değişken isimlendirme, $ işareti ve bu dolar işaretini 
takip eden değişken ismi ile yapılır.
Değişken isimleri latin alfabesinden büyük veya küçük harfleri içerebilir.
Değişken isimleri rakamları içerebilir.
Alt tire (_) karakteri içerebilir.
UTF-8 karakter kodlamasında bulunan karakterleri içerebilir.
Değişken isminin ilk karakteri rakam olamaz.
Değişken isimleri büyük küçük harfe duyarlıdır. Örneğin $sayi 
ile $Sayi ayni değişken değillerdir
*/

PHP'de her ifade aslında true ya da false değerine sahiptir. 
0 hariç tüm tamsayılar true olarak düşünülür.
0.0 hariç tüm kayan noktalı sayılar true olarak değerlendirilir. 
0 ve 0.0 sayıları ya da bunlara eşit olan ifadeler false olarak 
kabul edilir.
"", '' şekilinde hiç bir karakter içermeyen metin türünden ifadeler ve "0",'0' 
stringleri false, bunlar haricindeki tüm metin türünden ifadeler true olarak 
değerlendirilir.


== Değişkenlere Değer Atamak
Değişkenlere değer atamak için `=` operatörü kullanılır. 
Atama işleminde öncelik sağ tarafdadır. Yani önce `=` operatörünün sağ tarafı 
hesaplanır ve değer sol tarafdaki değişkene atanır.

[source,php]
$sayi1 = 7; // $sayi1 değişkenine 7 değeri atandı.
$sayi2 = $sayi1 // $sayi2 değişkenine $sayi1 değişkeninin değer atanır.
$sayi3 = $sayi1 + 6; // $sayi3 değişkeni 7+6 değerini alır.
$sayi3 = $sayi3 + 2; // $sayi3 = 13 + 2 olur ve $sayi3 değişkeninin yeni değeri 15 olur.

== Değişken Türleri
* Integer : Tamsayı türünden değişkenler ve sabitler için kullanılır.
* Double : Reel sayı türünden değişkenler ve sabitler için kullanılır.
* String : Metin türünden değişkenler ve sabitler için kullanılır.
* Array : Dizi türünden değişkenler ve sabitler için kullanılır.
* Boolean : Mantıksal ifade (true, false) içeren değişkenler ve sabitler için kullanılır.
* Object : Sınıf örneklerini saklmak için kullanılır.

== Sabitler$
Program içerisinde değişmez olarak kalacak değerlere sabitler denir. Sabitler değiştirilemez. 
PHP'de sabit oluşturmak için `define` fonksiyonu kullanılır. `define` fonksiyonu aşağıdaki şekilde 
kullanılır.
[source,php]
define(PI, 3.14);
$yaricap = 3;
$alan = PI * $yaricap * $yaricap;

Sabit isimleri oluştururken büyük harfler kullanılır. Ayrıca, sabit isimlerinin başında, değişkenlerden farklı olarak
`$` işareti bulunmaz.

== Operatörler
Operatörler, değerler ve değişkenler üzerinde belirli bir işlem yapan fonksiyon kısayollarıdır. Operatörler genellikle 
tek bir sembolden ibarettir. Bir operatör, solunda bulunan ifade ile sağında bulunan ifadeyi bir operasyona tabi tutar.
Örneğin, `+` operatörü solundaki sayı ile sağındaki sayıyı toplar.
[source,php]
$sayi = 3
$sayi1 = $sayi + 2; // $sayi1 = 5 olur.

=== Aritmetik Operatörler
|===
|Operatör |İsim |Örnek

|`+`
|Toplama
| `$a + $b`

|`-`
|Çıkarma
| `$a - $b`

|`*`
|Çarpma
| `$a * $b`

|`/`
|Bölme
| `$a / $b`

|`%`
|Kalan
| `$a % $b`
|===

=== String Operatörleri
İki string türünden değişkeni veya değeri bitişik şekilde birleştirmek için `.` operatörü kullanılır.
[source,php]
----
$ad = "Ali";
$bosluk = " ";
$soyad = "ŞAHİN"
$ad_soyad = $ad.$bosluk // $ad_soyad = "Ali " olur.
$ad_soyad = $ad_soyad.$soyad; // $ad_soyad = "Ali ŞAHİN"
$ad_soyad = $ad.$bosluk.$soyad; // $ad_soyad = "Ali ŞAHİN"
----



// 24.10.2017 GBIL201 Dersi Başlangıcı

== Birleşik Atama Operatörleri
Birleşik atama operatörleri, bir değişken üzerinde belli bir işlem yapıp 
sonucu yine aynı değişkene atamaya yarar.
Örneğin;
[source,php]
$a += 5;

ile
[source,php]
$a = $a + 5;

aynı işlevi görür.
|===
|Operatör |Kullanılışı |Eşiti

|`+=`
|`$a += $b`
|`$a = $a + $b`

|`-=`
|`$a -= $b`
|`$a = $a - $b`

|`*=`
|`$a *= $b`
|`$a = $a * $b`

|`/=`
|`$a /= $b`
|`$a = $a / $b`

|`%=`
|`$a %= $b`
|`$a = $a % $b`

|`.=`
|`$a .= $b`
|`$a = $a . $b`
|===

[source,php]
$ad = "Ali";
$bosluk = " ";
$soyad = "ŞAHİN"
$ad_soyad="";
$ad_soyad .= $ad; // $ad_soyad = ""."Ali" olur yani $ad_soyad="Ali"
$ad_soyad .= $bosluk; // $ad_soyad = "Ali"." " olur yani $ad_soyad="Ali "
$ad_soyad .= $soyad; // $ad_soyad = "Ali "."ŞAHİN" olur yani $ad_soyad="Ali ŞAHİN"

=== Bir Artırma ve Bir Azaltma Operatörleri
Değişken önüne veya sonuna koyulan `pass:[++]`, değişkenin değerini bir arttırır. Benzer şekilde 
değişken önüne veya sonuna koyulan `--` , değişkenin değerini bir azaltır. Yani; 
`pass:[$a++]` veya `pass:[++$a]` ifadeleri `a += 1` deyiminin kısayollarıdır.
// 18.10.2017 BIL201 Dersi Sonu

[source, php]
----
$sayi = 10;
$yeni_sayi = ++$sayi;
echo '$sayi : ' . $sayi; // $sayi=11 olur.
echo '<br />'; 
echo '$yeni_sayi : ' . $yeni_sayi; // $yeni_sayi = 11 olur.

$sayi = 10;
$yeni_sayi = $sayi++;
echo '$sayi : ' . $sayi; // $sayi=11 olur.
echo '<br />'; 
echo '$yeni_sayi : ' . $yeni_sayi; // $yeni_sayi = 10 olur.
----

=== Referanslar
Bir değişkene atama işlemi yapılırken, atanan değişkenin kopyasının mı kullanılacağını yoksa o değişkenin referansının mı kullanılacağının
seçimini yapabiliriz. Bu işlem `&` (ampersand) operatörü ile yapılır.
[source,php]
----
$a = 5;
$b = $a;

// Bu kodlar, $a nın bir kopyasını oluşturur ve bu ayrışık kopyayı $b değişkenine atar.
$a = 7;
// $a = 7 olarak atanırsa acaba, $b değişkeni de 7 mi olur?
// Bu kullanımda $a da gerçekleşen değişimler $b yi etkilemez.
echo '$b : ' . $b;
echo "<br />";


// Bu kodlar, $a nın referansını $b değişkenine aktarır.
$a = 5;
$b = &$a;

$a = 56;
// Bu $b de 56 olur.
echo '$b : ' . $b;
----

=== Karşılaştırma Operatörleri
İki değeri karşılaştırmak için kullanılır. Bu operatörleri kullanan ifadeler, karşılaştırmanın 
sonucunda, mantıksal değerler olan `true` veya `false` değerlerinden birini alır.

|===
|Operatör |Kullanılışı |Eşiti

|`==`
|eşittir
|`$a == $b`

|`===`
|denktir
|`$a === $b`

|`!=`
|eşit değildir
|`$a != $b`

|`<>`
|eşit değildir
|`$a <> $b`

|`<`
|küçüktür
|`$a < $b`
|`>`
|büyüktür
|`$a > $b`

|`pass:[<=]`
|küçük veya eşit
|`$a <= $b`

|`>=`
|büyük veya eşit
|`$a >= $b`
|===

=== Mantıksal Operatörler
Mantıksal operatörler, iki veya daha fazla mantıksal ifadenin sonuçlarını mantıksal olarak birleştirmek için kullanılır.

|===
|Operatör |Adı |Kullanılışı |Sonuç

|`!`
|NOT
|`!$a`
|`$a` `false` is `true`, `true` ise `false` değerini döndürür.

|`&&`
|AND
|`$a && $b`
|`$a` ile `$b` değişkenlerinin ikisi de `true` ise `true`,  aksi durumlarda `false` döndürür.

|`&#124;&#124;`
|OR
|`$a &#124;&#124; $b`
|`$a` ile `$b` değişkenlerinin ikisinden biri veya ikisi birden `true` ise `true`,  aksi durumlarda `false` döndürür.
|===

[source, php]
----
$yas = 15;
/*
Yaşı 0-3 arasında olanlara bebek;
Yaşı 4-18 arasında olanlar çocuk;
Yaşı 19-45 arasında olanlar yetişkin;
*/
if( ($yas >= 0) && ($yas <=3) ) {
    echo "Sen bir bebeksin";
}
elseif(($yas > 3) && ($yas <=18))
{
    echo "Sen bir çocuksun";
}
elseif(($yas > 18) && ($yas <=45))
{
    echo "Sen bir yetişkinsin";
}
----

[source, php]
----
<html>
	<head>

	</head>
	<body>

		<form action="online.php" method="post">
			1. Soru : Açık kaynaklı web programlama dili nedir?
			<br />
			<input type="text" name="soru_bir" />
			<br />
			2. Soru : Web sitesi tasarlamak için kullanılan dil nedir?
			<br />
			<input type="text" name="soru_iki" />
			<br />
			<input type="submit" name="test" value="Sınav Sonucumu Göster" />
		</form>
		<?php
		/*
		 * Sorulan iki sorudan en az birini bilen bir kişinin 
		 * başarılı kabul edildiği bir sınav için veya operatörünün kullanılışı.
		 */
		if(!empty($_POST["test"])) {
			$bir = ($_POST["soru_bir"] == "PHP");
			$iki = ($_POST["soru_iki"] == "HTML");

			if($bir or $iki) {
				echo "Sınavdan geçtiniz.";
			}
			else {
				echo "Sınavdan kaldınız.";
			}
		}
		?>
	</body>
</html>
----

=== Ternary Operatörü
`if-else` yapısının kısa şeklidir. Kullanım biçimi aşağıdaki gibidir +
`koşul ? koşul doğru ise değer : koşul yanlış ise değer`

[source, php]
----
<html>
    <head>
	<title>Zebra Stilli Tablo</title>
    </head>
<body>
<?php
echo "<table border='1'>";
$renk="purple";
for($i=1; $i<=15; $i++) {
	echo "<tr bgcolor=$renk><td>A</td><td>B</td></tr>";
	$renk = $renk == "purple" ? "yellow" : "purple";
}
echo "</table>";
?>
</body>
</html>
----
// 24.10.2017 GBIL201 Dersi Sonu

=== Hata Mesajı İptal Operatörü
PHP'de bir deyimin başına `@` operatörü getirildiğinde, bu deyimin üreteceği olası hata iletileri yok sayılır.

=== Operatör Öncelikleri ve Birleşmeleri
Bir operatör ikiden fazla ifade ile kullanıldığında birleşmenin hangi tarafdan başlayarak gerçekleşeciğini 
operatörün birleşme yönü ile tayin edebiliriz.
|===
|Birleşim Yönü |Operatörler

|sağ
|`!`

|sol
|* / %

|sol
|+ - .

|yönsüz
|< pass:[<=] > >=

|yönsüz
|== != === !== <>

|sol
|&

|sol
|&&

|sol
|`&#124;&#124;`

|sağ
|= += -= *= **= /= .= %=
|===
//25.10.2017 BIL201 Dersi Sonu
=== Değişken Fonksiyonları
Bir değişkenin tipi, içeriği gibi bilgileri öğrenmek veya sorgulamak için kullanılan fonksiyonlardır.
Bir değişkenin türünü öğrenemk için `gettype()` fonksiyonu kullanılır.

[source, php]
----
<?php
$degisken="Merhaba";
echo gettype($degisken); // string yazacaktır.

$degisken1=13;
echo gettype($degisken1); //integer yazacaktır.

$degisken2=1.45;
echo gettype($degisken2); //double yzacaktır.

$degisken3=false;
echo gettype($degisken3); //boolean yzacaktır.
?>
----
Bir değişkenin türünü değiştirmek içi `settype()` fonksiyonu kullanılır. `settype()` fonksiyonu 
iki argüman alır. Birinci argüman; türü değiştirilmek istenen değişken, ikinci argüman ise değişkenin yeni türünü
belirten metindir.
[source, php]
----
<?php
$a=56;
echo '$a değişkeninin türü : ' . gettype($a); // integer
echo "<br />";
settype($a, "double");
echo '$a değişkeninin yeni türü : ' . gettype($a); // double
?>
----
PHP ayrıca tip kontrol fonksiyonları da içerir. Bu fonksiyonlar, bir değişkeni argüman olarak alır ve o değiikenin 
ilgili türden olup olmadığını `true` veya `false`  döndürerek bildirir. Bu fonksiyonlar şunlardır:

* `is_array()`
* `is_double()`, `is_float()`, `is_real()`
* `is_long()`, `is_int()`, `is_integer()`
* `is_string()`
* `is_object()`

=== Değişkenin Durumunu Kontrol Etmek
`isset()` fonksiyonu ile bir değişkenin tanımlanıp tanımlanmadığı denetlenebilir. Değişken tanımlı ise `true`, 
tanımlı değilse `false` döndürür. +
Bir değişkenin tanımlı olup olmadığını `empty()` fonksiyonu ile de denetleyebiliriz. Ayrıca `empty()` fonksiyonu, bir değişkenin içeriğinin 
boş veya sıfır olup olmadığını da sınar.
//31.10.2017 GBil ders sonu

[source, php]
----
var_dump(isset($degisken));
/* Yukarıdaki ifadede; $degisken, isset fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmadığından(= operatörü ile bir değer ataması yok) bu
 * değişken tanımsızdır. Dönen değer false olacaktır.
*/
----

[source, php]
----
<?php
$degisken="Merhaba";
var_dump(isset($degisken));
/* Yukarıdaki ifadede; $degisken, isset fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlandığından(= operatörü ile bir değer ataması var) bu
 * değişken tanımlıdır. Dönen değer true olacaktır.
*/
?>
----

[source, php]
----
<?php
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmadığından(= operatörü ile bir değer ataması var) bu
 * değişken tanımsızdır ve dolayısıyla boş olarak düşünülebilir. empty fonksiyonu
 * boş değerde true döndürdüğü için, dönen değer true olacaktır.
 */
?>
----

[source,php]
----
<?php
$degisken="Merhaba";
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmış ve boş değer almamıştır. empty fonksiyonu, değişken
 * boş olmadığında false döndürdüğü için dönen değer false olacaktır.
 */
?>
----

[source, php]
----
<?php
$degisken="";
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmış ama boş değer almıştır. empty fonksiyonu, değişken
 * boş olduğunda true döndürdüğü için dönen değer true olacaktır.
 */
?>
----

[source, php]
----
<?php
$degisken=0;
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda 0 değerini almıştır. empty fonksiyonu, değişken
 * 0 değerini aldığında true döndürdüğü için dönen değer true olacaktır.
 */
?>
----

[source, php]
----
<?php
$degisken=1;
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda 0 değerini almamıştır. empty fonksiyonu, değişken
 * 0 değerini almadığında false döndürdüğü için dönen değer false olacaktır.
 */
?>
----

[source, php]
----
<html>
<head>
    <title>Araç Vergisi Hesapla</title>
</head>
<body>
<form action="online.php" method="post">
    Aracın Üretim Yılı : <input type="text" name="yil" />
    <input type="submit" name="submit" value="Hesapla" />
</form>
<?php
/* Bu program, üretim yılı girilen bir aracın vergi miktarı hesaplamaktadır.
 * Aracı vergi miktarı 1000 * (1 / Araç Yaşı) formülü ile elde edilmektedir.
 */
if(!empty($_POST)) {
    if(empty($_POST["yil"])) {
        echo "Araç üretim yılını boş girdiniz.!";
    }
    else {
        $arac_uretim_yili = $_POST["yil"];
        settype($arac_uretim_yili, "integer");
        $arac_yasi = 2017 - $arac_uretim_yili + 1;
        $vergi_miktari = 1000 * (1/$arac_yasi);
        echo $vergi_miktari;
    }
}
?>
</body>
</html>
----
=== Kontrol Yapıları
==== If Deyimi
`If-else` yapısı, bir koşulun sağlanması ve sağlanmaması durumunda farklı kod bloklarının çalışmasını sağlar.
Kullanım şekli aşağıdaki gibidir.
[source, php]
----
if(koşul) {
	// koşul true ise yapılacaklar
}
else {
	// koşul false ise yapılacaklar
}
----

[source, php]
----
<?php
$yas = 2;
if($yas < 4) {
    echo "Bebek";
}
elseif($yas < 12) {
    echo "Çocuk";
}
elseif($yas < 30) {
    echo "Genç";
}
/* if - elseif yapısındaki koşullardan biri sağlandığında o blok çalıştırılır.
 * Sonraki elseif blokları işletilmez.
 * Yukarıdaki örnekte; 2<4, 2<12 ve 2<30 olup bütün elseif bloklarının koşulu sağlanır ama ilk
 * koşulu sqğlaya elseif bloğu 2<4 olduğu için program Bebek çıktısı üretecektir.
 */
?>
----
//01.11.2017 BIL Ders Sonu


==== `switch-case` Yapısı
`switch-case` yapısı `if-elseif-else` yaspısı ile eşdeğer olarak düşünülebilir. Eğer `if-elseif-else` yapısında 
kullanılan koşullar basit ve değer formunda ise bu yapı yerine `switch-case` yapısı kullanmak daha uygun olacaktır."

[source, php]
----
<html>
<head>
    <title>Tek Soruluk Sınav</title>
</head>
<body>
<form action="online.php" method="post">
    <table border="1">
        <tr>
            <td>1.</td>
            <td>Aşağıdakilerden hangisi PHP de bir değişkenin içeriği boş ise true döndürür?</td>
        </tr>
        <tr>
            <td>
                <input type="radio" value="a" name="soru1"><br />
                <input type="radio" value="b" name="soru1"><br />
                <input type="radio" value="c" name="soru1"><br />
                <input type="radio" value="d" name="soru1"><br />
            </td>
            <td>
                A) var_dump() <br />
                B) echo() <br />
                C) empty() <br />
                D) isset()
            </td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" name="submit" value="Sınavı Bitir" /></td>
        </tr>
    </table>
</form>
<?php
if(!empty($_POST)) {
    switch($_POST["soru1"]) {
        case "a" :
            echo "Yanlış Cevap";
            break;
        case "b" :
            echo "Yanlış Cevap";
            break;
        case "c" :
            echo "Doğru Cevap";
            break;
        case "d" :
            echo "Yanlış Cevap";
            break;
        default :
            echo "Ne girdiğinizi anlayamadım.";
            break;
    }
}
?>
</body>
</html>
----
==== `while` Döngüsü
Bir koşul doğru olduğu sürece bloğunu tekrarlaya döngüdür. Kullanım şekli aşağıdaki gibidir.
[source, php]
----
while(koşul) {
  /* koşul doğru ise bu bloğun içi işletilecek ve bloğun sonuna 
   * gelindiğinde tekrar koşul sınanacak ve doğru olması durumunda 
   * blok yine baştan sona tekrar işlenecektir. Bu durum koşul yanlış 
   * oluncaya kadar devam eder. Koşulun yanlış olması durumunda while 
   * bloğununun bittiği yerden program devam eder.
   */
}
----
[source,php]
----
<html>
<head>
    <title>Sayıya En Yakın Üçe Bölünen Sayı</title>
</head>
<body>
<form action="online.php" method="post">
    Bir sayı giriniz : <input type="text" name="sayi" />
    <input type="submit" name="submit" value="Gönder" />
</form>
<?php
if(!empty($_POST)) {
    $sayi = intval($_POST["sayi"]);
    while($sayi >= 0) {
        if(($sayi % 3) == 0)
            break;
        $sayi--;
    }
    echo "Girdiğiniz sayıdan küçük ve o sayıya en yakın üçe bölünen sayı $sayi dır.";
}
?>
</body>
</html>
----
.{nbsp} 
==========================
Yukarıdaki örnekde, girilen sayıdan küçük olan ve girilen sayıya en yakın olan tamsayı bulunmuştur. Siz de 
girilen sayıya en yakın üçe bölünene sayıyı bulan bir program yazınız.
==========================


==== `for` Döngüsü
Döngü sayısı, döngünün başlayacağı ve biteceği değerler kesinlik arz ediyorsa for döngüsü tercih edilir. `for` dögngüsünün
yapısı aşağıdaki biçimdedir.
[source, php]
----
for(ifade1; koşul; ifade2) {
	ifade3;
	ifade4;
}
ifade5;
----
Görüldüğü gibi `for` döngüsünün özellikleri, `for` ifadesinden sonra gelen parantezin içinde yer alan ve birbirinden `;` 
karakteri ile ayrılan üç kısım ile oluşturulur.

* Program for döngüsüne geldiğinde bir defalığına `ifade1` çalıştırılır.
* Daha sonra `koşul` ifadesine bakılır. Eğer koşul doğru ise döngü bloğu yani burada  `ifade3` ve `ifade4` çalıştırılır. 
Eğer `koşul` doğru değil ise döngüye hiç girilmez ve döngü sonuna yani `ifade5` ifadesine atlanır.
* `koşul` koşulunun doğru olması durumunda döngü bloğu calışacak ve döngü adımı sonlandığında yeni adıma geçmeden önce 
`ifade2` çalıştırılır.
* Daha sonra `koşul` tekrar kontrol edilerek aynı işlemler devam eder.

[source,php]
----
<html>
<head>
    <title>for Döngüsü</title>
</head>
<body>
<?php
for($i=0; $i<=15; $i++) {
    echo "$i,";
}
?>
</body>
</html>
----

[source,php]
----
<html>
<head>
    <title>for Döngüsü</title>
</head>
<body>
<?php
for(ifade1; ifade2; ifade3) {
    ifade4;
    ifade5;
}
ifade6;

// Yukarıda for yapısına tam olarak karşılık gelen while yapısı aşağıda verilmiştir. 

ifade1;
while(ifade2) {
    ifade4;
    ifade5;
    ifade3;
}
ifade6;
?>
</body>
</html>
----

==Diziler
Diziler, birbiriyle ilişkili verileri tek bir değişken içinde saklamak
için kullanılır. Böylelikle, her bir ilişkili veri için ayrı bir değişken
kullanmak zorunda kalmayız. Bir sınıftaki tüm öğrencilerin ad soyadlarını
programda kullanacakasak, dizi yapısı olmasaydı her bir ad soyad için 
bir değişken oluşturmak zorunda kalırdıdık.

[source,php]
----
<?php
$ahmet_ali = "Ahmet Ali";
$ali_kaya = "Ali Kaya";
$ayse_cetin = "Ayşe Çetin";

$kirmizi_mermer = "Red"

$ad_soyad_1 = "Ahmet Ali";
$ad_soyad_2 = "Ali Kaya";
$ad_soyad_3 = "Ayşe Çetin";

$ad_soyad[1] = "Ahmet Ali";
$ad_soyad[2] = "Ali Kaya";
$ad_soyad[3] = "Ayşe Çetin";

$ad_soyad
?>
----


[source,php]
----
<?php
$ogrenciler = array(
    "Ahmet KAYA",
    "Ali ŞAHİN",
    "Zeynep ARSLAN",
    "Ali Akif Bir",
    "Ayşe SAYIN",
    "Meltem AKAR",
    "Hasan Ali TAŞ",
    "Mehmet EKER"
);
for($i=0; $i < count($ogrenciler); $i++ ) {

    $parcali_isim = explode(" ", $ogrenciler[$i]);
    if(count($parcali_isim) > 2) {
        echo $parcali_isim[0][0] . ". " . $parcali_isim[1] . " " . $parcali_isim[2];
    }
    else {
        echo $ogrenciler[$i];
    }
    echo "<br />";
}
?>
----

[source,php]
----
<?php
$ogrenciler = array(
    "Ahmet KAYA",
    "Ali ŞAHİN",
    "Zeynep ARSLAN",
    "Ali Akif Bir",
    "Ayşe SAYIN",
    "Meltem AKAR",
    "Hasan Ali TAŞ",
    "Mehmet EKER"
);


foreach ($ogrenciler as $ogrenci) {

    $parcali_isim = explode(" ", $ogrenci);
    if(count($parcali_isim) > 2) {
        echo $parcali_isim[0][0] . ". " . $parcali_isim[1] . " " . $parcali_isim[2];
    }
    else {
        echo $ogrenci;
    }
    echo "<br />";


}
?>
----
[source,csv]
----
123|Ahmet Ali|Bilgisayar Programcılığı|Matematik|45|63
123|Ahmet Ali|Bilgisayar Programcılığı|Fizik|35|73
124|Zeynep ŞAHİN|Moda Tasarımı|Tekstil|55|63
124|Zeynep ŞAHİN|Moda Tasarımı|Meslek Etiği|55|63
125|Hasan KAÇAN|Elektrik|Matematik|12|87
125|Hasan KAÇAN|Elektrik|Fizik|12|87
125|Akif TAŞ|Elektrik|Matematik|22|37
125|Akif TAŞ|Elektrik|Fizik|32|12
----




[source,php]
----
<?php
$ogrenciler = array(
    102 => "Ali ŞAHİN",
    103 => "Zeynep BULUT",
    501 => "Metin TEKİN"
);
echo $ogrenciler[501];

$notlar = array(
   array(
        "adi_soyadi" => "Ali Veli",
        "numarasi" => 134,
        "vize" => 45,
        "final" => 85
    ),
    array(
        "adi_soyadi" => "Ali KAYA",
        "numarasi" => 143,
        "vize" => 65,
        "final" => 85
    ),
    array(
        "adi_soyadi" => "Zeynep KAYA",
        "numarasi" => 135,
        "vize" => 5,
        "final" => 75
    )

);

echo $notlar[1]["numarasi"];


?>
----

[source, php]
----
<?php


if(isset($_POST["sonhal"])) {
    $sayilar = explode(",", $_POST["sonhal"]);
}

$mesaj = "";


if(!empty($_POST)) {
    $tahmini = $_POST["tahmin"];
    $dizi_son_eleman = $sayilar[count($sayilar)-1];
    if($tahmini == $dizi_son_eleman) {
        array_pop($sayilar);
        $mesaj = "Tebrikler bildiniz.". sizeof($sayilar) . " sayı kaldı";
    }
    else {
        $mesaj = "Bilemediniz. Tekrar deneyiniz.";
    }
}

?>
<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>"
<label for="tahmin">Tahmin Et</label>
<input type="text" name="tahmin" />
<input type="hidden" name="sonhal" value="<?php echo implode(',', $sayilar) ?>" />
<input type="submit" value="Gönder" />
<br>
<?php echo $mesaj ?>

</form>


----

=== PHP'De Dizi Türleri

İndeksli Diziler : Dizi elemanlarına erişmek için sayısal değerler
kullanılır.

İlişkisel Diziler : Dizi elemanlarına erişmek için string türünde 
sabitler kullanılır.

Çok Boyutlu Diziler : Dizinin elemanları da bir dizi olabilir.


//07.11.207 GBIL Ders sonu
=== MySQL ve PHP
PHP'de MySQL veritabanına bağlantı kurmak ve temel veri işlemlerini yapmak için 
PDO(PHP Data Objects) sınıfı kullanılır.

==== Veritabanı Sunucusuna Bağlanma
Veritabanı bağlantısı kurmak için öncelikle bir PDO nesnesi oluşturulur. Bir PDO nesnesi 
[source, php]
----
$db = new PDO($dsn, $username, $password);
----
PDO sınıfının kurucu fonksiyonu görüldüğü gibi üç argümana htiyaç duyar. Bunlar DSN(Data Source Name), 
veritabanı sunucusunun kullanıcı ismi ve şifresi. DSN, veritabanı sunucusunun türü, adresi ve kullanılacak veritabanını tanımlar.
DSN'nin söz dizimi aşağıdaki gibidir.

[source, php]
----
$dsn = "mysql:host=host_adresi;dbname=veritabani";
----

==== İstisnaları Yakalamak
PDO sınıfından bir PDO nesnesi türetirken bir hata ve olağan dışı durumlarla karşılaşabilirsiniz. 
Örneğin, bağlanmak istediğiniz veritabanı sunucusunun hizmeti sonlandırılmış olabilir. 
Böyle istisnai durumları yakalamak için `try-catch` yapısı kullanılır. Eğer istisnalar yakalanmazsa 
programın çalışmayı durdurur.

[source, php]
----
try {
	$db = new PDO("mysql:host=localhost;dbname=veritabani", "root", "12345");
}
catch(PDException $e) {
	$error_mesage = $e->getMessage();
}
----

==== Ürün Gösterme Uygulaması Örneği
Müzik aletleri satan bir mağazanın online kataloğunu oluşturmak için kullancağımız uygulama.
Uygulamanın veritabanı için aşağıdaki sql dosyasını kullanacağız.

[source, php]
----
-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Dec 19, 2017 at 03:19 PM
-- Server version: 5.7.19
-- PHP Version: 5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `magaza`
--

-- --------------------------------------------------------

--
-- Table structure for table `kategoriler`
--

DROP TABLE IF EXISTS `kategoriler`;
CREATE TABLE IF NOT EXISTS `kategoriler` (
  `kategori_id` int(11) NOT NULL AUTO_INCREMENT,
  `kategori_ismi` varchar(100) COLLATE utf8_turkish_ci NOT NULL,
  PRIMARY KEY (`kategori_id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Dumping data for table `kategoriler`
--

INSERT INTO `kategoriler` (`kategori_id`, `kategori_ismi`) VALUES
(1, 'Gitarlar'),
(2, 'Baslar'),
(3, 'Davullar');

-- --------------------------------------------------------

--
-- Table structure for table `urunler`
--

DROP TABLE IF EXISTS `urunler`;
CREATE TABLE IF NOT EXISTS `urunler` (
  `urun_id` int(11) NOT NULL AUTO_INCREMENT,
  `urun_kod` varchar(50) COLLATE utf8_turkish_ci NOT NULL,
  `urun_isim` varchar(500) COLLATE utf8_turkish_ci NOT NULL,
  `urun_fiyat` float NOT NULL,
  `kategori_id` int(11) NOT NULL,
  PRIMARY KEY (`urun_id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Dumping data for table `urunler`
--

INSERT INTO `urunler` (`urun_id`, `urun_kod`, `urun_isim`, `urun_fiyat`, `kategori_id`) VALUES
(1, 'slen', 'St. Lenov', 799, 1),
(2, 'kpol', 'Ken Paul', 1199, 1),
(3, 'tmox', 'Ten Mox', 500, 1),
(4, 'clam', 'Clm Maxi', 700, 2),
(5, 'rol', 'Ron Loul', 456, 2),
(6, 'yul', 'Young Lul', 123, 3);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
----

Web sunucumuzun kök dizininde(Wamp için `C:\wamp64\www`) `product_viewer` isimli bir klasör oluşturalım. Bu uygulamanın bütün dosyalarını 
bu klasör içinde oluşturacağız. Veritabanına bağlanma prosedürünü proje genelinde bir çok dosyada tekrar edeceğimizden dolayı, bu işlemi gerçekleştiren bir php dosyası 
oluşturmak ve bu dosyayı diğer dosyaların içine aktarmak daha mantıklı olacaktır. Bu işlem için, bulunduğunuz dosyaya başka bir dosyayı 
dahil etmeye yarayan `include()` fonksiyonu kullanılabilir. Veritabanına bağlanma prosedürünü yerine getiren `database.php` dosyasını 
ve veritabanına bağlanırken oluşabilecek hataları göstermeye yarayacak `database_error.php` dosyasını oluşturalım. `database_error.php` 
dosyasını `database.php` dosyası içine dahil edeceğimizden, öncelikle `database_error.php` dosyasını oluşturalım.

.database_error.php
[source, php]
----
<!DOCTYPE html>
<html>
<head>
    <title>Mağaza</title>
</head>
<body>
	<h1>Veritabanı Hatası</h1>
	<p>Veritabanına bağlanırken aşağıdaki hata oluştu.</p>
	<?php echo $error_message; ?>
</body>
</html>
----

.database.php
[source, php, highlight='7-10']
----
<?php
$dsn = "mysql:host=localhost;dbname=magaza;charset=utf8";
$username="root";
$password="";

try {
    $db = new PDO($dsn, $username, $password); // <1>
}
catch(PDOException $e) {
    $error_message = $e->getMessage();
    include("database_error.php"); // database_error.php dosyası bu satıra yerleşiyor.
    exit();
}
?>
----

Uygulamamız ürün listeleme sayfası iki sütundan oluşmaktadır. Sol sütunda, her bir kategori ismi bağlantı olacak şekilde kategoriler listesi; 
sağ tarafta ise soldan hangi kategoriye tıklandıysa on ait ürünlerin listesi.

.index.php
[source, php]
----
<?php
require_once("database.php");

$category_id = filter_input(INPUT_GET, 'category_id', FILTER_VALIDATE_INT);

if($category_id == NULL || $category_id == FALSE) {
    $category_id = 1;
}

$queryCategory = 'SELECT * FROM kategoriler WHERE kategori_id = :kat_id';
$statement1 = $db->prepare($queryCategory);
$statement1->bindValue(':kat_id', $category_id);
$statement1->execute();
$category = $statement1->fetch();
$category_name = $category['kategori_ismi']; // tıklanan kategorinin ismi $category_name değişkeninde saklı.
$statement1->closeCursor();

// Bütün kategorileri çek
$queryAllCategories = 'SELECT * FROM kategoriler ORDER BY kategori_id';
$statement2 = $db->prepare($queryAllCategories);
$statement2->execute();
$categories = $statement2->fetchAll(); // bütün kategori kayitlar $categories değişkeni içinde
$statement2->closeCursor();

$queryProducts = 'SELECT * FROM urunler WHERE kategori_id = :kat_id ORDER BY kategori_id';
$statement3 = $db->prepare($queryProducts);
$statement3->bindValue(':kat_id', $category_id);
$statement3->execute();
$products = $statement3->fetchAll(); // tıklanan kategoriye ait ürün kayıtları $products değişkenine atandı.
$statement3->closeCursor();
?>
<!DOCTYPE HTML>
<html>
<head>
    <title>Müzik Aletleri Mağazası</title>
</head>
<body>
    <main>
        <h1>Ürünler Listesi</h1>
        <aside>
            <h2>Kategoriler</h2>
            <nav>
                <ul>
                    <?php foreach($categories as $category) : ?>
                        <li>
                            <a href='?category_id=<?php echo $category['kategori_id']; ?>'>
                                <?php echo $category['kategori_ismi']; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </aside>

        <section>
            <h2><?php echo $category_name; ?></h2>
            <table border="1">
                <tr>
                    <th>Kodu</th>
                    <th>İsmi</th>
                    <th>Fiyatı</th>
                </tr>

                <?php foreach($products as $product) : ?>
                    <tr>
                        <td><?php echo $product['urun_kod']; ?></td>
                        <td><?php echo $product['urun_isim']; ?></td>
                        <td><?php echo $product['urun_fiyat']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </section>
    </main>
</body>
</html>
----


[source, php]
----
// Varsayılan anahtarlama (0,1,2,3...) kullanan bir dizi oluşturma
$isimler = array("ali", "ahmet", "akif");
$sansli_sayilar = array(3, 5, 11, 45, 23, 32);

// $isimler dizisinde "ahmet" değerine ulaşmak için aşağıdaki yapı kullanılır.
echo $isimler[1];
// Burada köşeli parantezler içerisine yazılan 1 sayısı ahmet değerinin
// $isimler dizisi içindeki anahtarıdır.

// Varsayılan anahtarlama ile dizi oluşturmak için aşağıdaki yöntem de kullanılabilir.
$isimler = ["ali", "ahmet", "akif"];
$sansli_sayilar = [3, 5, 11, 45, 23, 32];

// Ayrıca boş bir dizi oluşturmak için
$bos_dizi = array();
// veya
$bos_dizi = [];
// ifadeleri kullanılabilir.

// İsteğe bağlı anahtarlama yapılmak istendiğinde, dizinin elemanları 
// anahtar => değer biçiminde yazılır.

$kisi_bilgileri = ["hasan", "ökten", 1980, "denizli"];

// Yukarıdaki dizi daha anlamlı anahtarlama ile
$kisi_bilgileri = ["adi" => "hasan", "soyadi" => "ökten", "dogrumtarihi" => 1980 , "dogumyeri" => "denizli"];
// Kodun sadeliği için aşağıdaki yöntem kullanılır.
$kisi_bilgileri = [
    "adi" => "hasan",
    "soyadi" => "ökten",
    "dogumtarihi" => 1980, 
    "dogumyeri" => "denizli"
    ];
// $kisi_bilgileri dizisinde 1980 değerine ulaşmak için
$kisi_bilgileri["dogumtarihi"]; // 1980
// ifadesi kullanılır.

// $kisi_bilgileri dizisine anahtar kullanarak bir değer eklenebilir.
$kisi_bilgileri["medenihali"] = "Evli";

// Bir diziye eleman eklemek için aşağıdaki yöntem kullamılabilir.
$cift_sayilar = [0, 2, 4, 6];
$cift_sayilar[] = 8;
// $cift_sayilar = [0, 2, 4, 6, 8] olacaktır
----

=== Dizini Eleman Sayısını Bulma
Bir dizinin toplam eleman sayısını bulmak için `count()` fonksiyonu kullanılır.

[source, php]
----
$meyveler = array("elma", "armut", "portakal");
$meyve_sayisi = count($meyveler);
echo "Sepetde $meyve_sayisi tane meyve var";
---- 

=== Dizini Elemanlarını Döngüde Kullanmak
Bir dizinin tüm elemanları ile teker teker yapacağınız işlemler varsa 
bu dizinin elemanlarını bir döngü yardımıyla taramamız gerekir.
Döngü ile dizinin ilk elemanında son elemanına kadar bütün elemanlarını 
döngü içerisinde kullanabiliriz. Bu işlem değişik biçimlerde yapılabilir.

[source, php]
----
$dogum_tarihleri= [1980, 2000, 1965];
$dogum_tarihleri[0];
$dogum_tarihleri[1];
$dogum_tarihleri[2];

for($i=0; $i<=count($dogum_tarihleri)-1; $i++) {
    $yas = 2018 - $dogum_tarihleri[$i];
    echo "Yaşı $yas<br />";

}

    /*
        $cift_sayilar = [0, 2, 4, 6];
        var_dump($cift_sayilar);

        $cift_sayilar[] = 8;
        var_dump($cift_sayilar);

        $kisi_bilgileri = [
            'adi' => 'ali',
            'soyadi' => 'demir'
        ];
        var_dump($kisi_bilgileri);
        $kisi_bilgileri[] = 1980;
        var_dump($kisi_bilgileri);

        $kisi_bilgileri = [
            'adi' => 'ali',
            'soyadi' => 'demir',
            3 => "denizli"
        ];
        var_dump($kisi_bilgileri);
        $kisi_bilgileri[] = 1980;
        var_dump($kisi_bilgileri);
        */
$dogum_tarihleri= [1980, 2000, 1965];

for($i=0; $i<=count($dogum_tarihleri)-1; $i++) {
    $yas = 2018 - $dogum_tarihleri[$i];
    echo "Yaşı $yas<br />";
}
$j=0;

while($j<=count($dogum_tarihleri)-1) {
    $yas = 2018 - $dogum_tarihleri[$j];
    echo "Yaşı $yas<br />";
    $j++;
}

foreach($dogum_tarihleri as $dtarihi) {
    $yas = 2018 - $dtarihi;
    echo "Yaşı $yas<br />";
}




$kisiler = [
    "adi" => "hasan",
    "soyadi" => "ökten",
    "dogumtarihi" => 1980
];


foreach($kisiler as $deger) {
    echo "Deger : $deger <br />";
}


foreach($kisiler as $anahtar => $deger) {
    echo "Anahtarı $anahtar olan elemanın değeri $deger <br />";
}

----

[source, php]
----
<html>
<?php
$arkaplan="white";
if(!empty($_POST)) $arkaplan = $_POST["renk"];
?>
<style>
.tek {
    background-color : #dddddd;
}
.cift {
    background-color : yellow;
}
</style>
<body>
<?php

$yemekler = array(
    "kahvalti" => "Tereyağ, Menemen, Çay",
    "ogle" => "Fasulye, Makarna, Ayran",
    "aksam" => "Tas Kebabı, Pilav, Salata"
);
echo "<table border='1'>";
$stil = "tek";
foreach($yemekler as $ogun => $yemek) {
    echo "<tr class='$stil'>";
    echo "<td>$ogun</td>";
    echo "<td>$yemek</td>";
    echo "</tr>";
    $stil = $stil=="tek" ? "cift" : "tek";
}
echo "</table>";
?>
</body>
</html>
----

[source, php]
----
<?php
echo "Döngüden önceki satır."
for ($i = 1; $i <= 3; $i++) {
    echo $i;
    echo "Bitti";
}
----
Program 4. satıra geldiğinde, programımız for döngüsünün başlangıç ifadesi adı verilen ve ilk noktalı virgüle kadar olan ifadeyi hiçbir koşul gözetmeksizin çalıştıracaktır. O halde, 4. satıra gelindiğinde $i=1 olacaktır. 

Yine 4. satırda, bu işlemini hemen sonrasında döngünün çalışıp çalışmayacağını anlamak için, birinci ; ile ikinci ; arasında kalan ifadenin sonucuna bakılır. Eğer bu sonuç true ise döngünün kod bloğu çalıştırılmaya başlanır ve program 5.satırdan(döngünün kod bloğunun başı) 6. satıra(döngünün kod bloğunun sonu) kadar çalıştırılır. 

6. satır çalıştıktan sonra döngünün kod bloğu baştan sona çalıştırılmış olur.
Program tekrar for satırına geri dönüp for deyiminin ikinci ; karakterinden sonra gelen bitiş ifadesi çalıştırır.

Sonrasında tekrar koşul ifadesine bakılır. Eğer koşul ifadesi doğru ise aynı işlemler tekrarlanır. Eğer koşu ifadesi false ise döngünün kod bloğunun bittiği yerden(8. satır) program devam eder. 

[source, php]
----
echo "Döngüden önceki satır.\n";
for ($i = 1; $i <= 3; $i++) {
    echo "Adım $i\n";

}
echo "Döngüden sonraki satır.\n";
----
Yukarıdaki döngü ile aşağıdaki döngü birbirinin aynısıdır. 

[source, php]
----
echo "Döngüden önceki satır.\n";
for ($i = 1; $i <= 3;) {
    echo "Adım $i\n";
     $i++;
}
echo "Döngüden sonraki satır.\n";
----


[source, php]
----
echo "Döngüden önceki satır.\n";
{
$i = 1
for (; $i <= 3; $i++) {
    echo "Adım $i\n";
}
}
echo "Döngüden sonraki satır.\n";
----
Yukarıdaki döngü ile aşağıdaki döngü birbirinin aynısıdır. 

[source, php]
----
echo "Döngüden önceki satır.\n";
for ($i = 1; $i <= 3; $i++) {
    echo "Adım $i\n";
}
echo "Döngüden sonraki satır.\n";
----
[source, php]
----
<?php
$yazi="DENEME";

for($i=0; $i<strlen($yazi); $i++) {
    for($j=0; $j<=$i; $j++) {
        echo $yazi[$j];
    }
    echo "\n";
}

// Bir metnin herhangi bir kesitini bulmak
$yazi = "Merhaba Dünya";

$bas=2;
$son=5;
for($i=$bas; $i<=$son; $i++) {
    echo $yazi[$i];
}
----



[source, php]
----
<?php
$ogrenciler = [
    1233 => "Ali Demir",
    1234 => "Ali Veli",
    1235 => "Fatma Şahin",
    1236 => "Bekir Kavruk"
    ];


for($i=1234; $i<=1236; $i++) {
    echo $ogrenciler[$i];
    echo "\n";
}

foreach($ogrenciler as $isim) {
    echo $isim;
    echo "\n";
}

foreach($ogrenciler as $numara => $isim) {
    echo "Numarası $numara, adı soyadı $isim\n";
}
----


[source, php]
----
<?php
$sifre = "DENEmfmfff";
if (strlen($sifre) <= 6) {
    echo "Şifre alanı 6 karakterden fazla olmalıdır.";
}
else {
    echo "Şifreniz geçerli.";
}

$kulismi = "alidemi";
$sifre = "12345";

if($kulismi=="alidemir") {
    if($sifre=="12345") {
        echo "Kullanıcı ismi ve şifreniz doğru.";
    }
    else {
        echo "Şifreniz yanlış";
    }
}
else {
    echo "Kullanıcı isminiz yanlış";
}

if($kulismi=="alidemir" && $sifre=="12345") {
    echo "Kullanıcı ismi ve şifreniz doğru.";
    
}
else {
    echo "Kullanıcı ismi veya şifreniz yanlış";
}
----


[source, php]
----
<?php
$yas=80;

if($yas<=3) {
    echo "Bebek";
}
elseif ($yas<=18) {
    echo "Çocuk";
}
else if ($yas<=45) {
    echo "Genç";
}
else if($yas<=75) 
    echo "Yaşlı";
else 
    echo "Allah uzun ömür versin.";
----


[source, php]
----
<?php
$ad="Ali";

if($ad=="Ali") {
    echo "Adı Ali\n";
    echo "If blok içi\n";
}
echo "If deyiminin sonu\n";


if($ad=="Ali"):
    echo "Adı Ali\n";
    echo "If blok içi\n";
    echo "If deyiminin sonu\n";
else:
    echo "Tersi";
endif;
----
