= Hello, AsciiDoc!
Doc Writer <doc@example.com>

== Değişkenlere Değer Atamak
Değişkenlere değer atamak için `=` operatörü kullanılır. 
Atama işleminde öncelik sağ tarafdadır. Yani önce `=` operatörünün sağ tarafı 
hesaplanır ve değer sol tarafdaki değişkene atanır.

[source,php]
$sayi1 = 7; // $sayi1 değişkenine 7 değeri atandı.
$sayi2 = $sayi1 // $sayi2 değişkenine $sayi1 değişkeninin değer atanır.
$sayi3 = $sayi1 + 6; // $sayi3 değişkeni 7+6 değerini alır.
$sayi3 = $sayi3 + 2; // $sayi3 = 13 + 2 olur ve $sayi3 değişkeninin yeni değeri 15 olur.

== Değişken Türleri
* Integer : Tamsayı türünden değişkenler ve sabitler için kullanılır.
* Double : Reel sayı türünden değişkenler ve sabitler için kullanılır.
* String : Metin türünden değişkenler ve sabitler için kullanılır.
* Array : Dizi türünden değişkenler ve sabitler için kullanılır.
* Boolean : Mantıksal ifade (true, false) içeren değişkenler ve sabitler için kullanılır.
* Object : Sınıf örneklerini saklmak için kullanılır.

== Sabitler
Program içerisinde değişmez olarak kalacak değerlere sabitler denir. Sabitler değiştirilemez. 
PHP'de sabit oluşturmak için `define` fonksiyonu kullanılır. `define` fonksiyonu aşağıdaki şekilde 
kullanılır.
[source,php]
define(PI, 3.14);
$yaricap = 3;
$alan = PI * $yaricap * $yaricap;

Sabit isimleri oluştururken büyük harfler kullanılır. Ayrıca, sabit isimlerinin başında, değişkenlerden farklı olarak
`$` işareti bulunmaz.

== Operatörler
Operatörler, değerler ve değişkenler üzerinde belirli bir işlem yapan fonksiyon kısayollarıdır. Operatörler genellikle 
tek bir sembolden ibarettir. Bir operatör, solunda bulunan ifade ile sağında bulunan ifadeyi bir operasyona tabi tutar.
Örneğin, `+` operatörü solundaki sayı ile sağındaki sayıyı toplar.
[source,php]
$sayi = 3
$sayi1 = $sayi + 2; // $sayi1 = 5 olur.

=== Aritmetik Operatörler
|===
|Operatör |İsim |Örnek

|`+`
|Toplama
| `$a + $b`

|`-`
|Çıkarma
| `$a - $b`

|`*`
|Çarpma
| `$a * $b`

|`/`
|Bölme
| `$a / $b`

|`%`
|Kalan
| `$a % $b`
|===

=== String Operatörleri
İki string türünden değişkeni veya değeri bitişik şekilde birleştirmek için `.` operatörü kullanılır.
[source,php]
----
$ad = "Ali";
$bosluk = " ";
$soyad = "ŞAHİN"
$ad_soyad = $ad.$bosluk // $ad_soyad = "Ali " olur.
$ad_soyad = $ad_soyad.$soyad; // $ad_soyad = "Ali ŞAHİN"
$ad_soyad = $ad.$bosluk.$soyad; // $ad_soyad = "Ali ŞAHİN"
----



// 24.10.2017 GBIL201 Dersi Başlangıcı

== Birleşik Atama Operatörleri
Birleşik atama operatörleri, bir değişken üzerinde belli bir işlem yapıp 
sonucu yine aynı değişkene atamaya yarar.
Örneğin;
[source,php]
$a += 5;

ile
[source,php]
$a = $a + 5;

aynı işlevi görür.
|===
|Operatör |Kullanılışı |Eşiti

|`+=`
|`$a += $b`
|`$a = $a + $b`

|`-=`
|`$a -= $b`
|`$a = $a - $b`

|`*=`
|`$a *= $b`
|`$a = $a * $b`

|`/=`
|`$a /= $b`
|`$a = $a / $b`

|`%=`
|`$a %= $b`
|`$a = $a % $b`

|`.=`
|`$a .= $b`
|`$a = $a . $b`
|===

[source,php]
$ad = "Ali";
$bosluk = " ";
$soyad = "ŞAHİN"
$ad_soyad="";
$ad_soyad .= $ad; // $ad_soyad = ""."Ali" olur yani $ad_soyad="Ali"
$ad_soyad .= $bosluk; // $ad_soyad = "Ali"." " olur yani $ad_soyad="Ali "
$ad_soyad .= $soyad; // $ad_soyad = "Ali "."ŞAHİN" olur yani $ad_soyad="Ali ŞAHİN"

=== Bir Artırma ve Bir Azaltma Operatörleri
Değişken önüne veya sonuna koyulan `pass:[++]`, değişkenin değerini bir arttırır. Benzer şekilde 
değişken önüne veya sonuna koyulan `--` , değişkenin değerini bir azaltır. Yani; 
`pass:[$a++]` veya `pass:[++$a]` ifadeleri `a += 1` deyiminin kısayollarıdır.
// 18.10.2017 BIL201 Dersi Sonu

[source, php]
----
$sayi = 10;
$yeni_sayi = ++$sayi;
echo '$sayi : ' . $sayi; // $sayi=11 olur.
echo '<br />'; 
echo '$yeni_sayi : ' . $yeni_sayi; // $yeni_sayi = 11 olur.

$sayi = 10;
$yeni_sayi = $sayi++;
echo '$sayi : ' . $sayi; // $sayi=11 olur.
echo '<br />'; 
echo '$yeni_sayi : ' . $yeni_sayi; // $yeni_sayi = 10 olur.
----

=== Referanslar
Bir değişkene atama işlemi yapılırken, atanan değişkenin kopyasının mı kullanılacağını yoksa o değişkenin referansının mı kullanılacağının
seçimini yapabiliriz. Bu işlem `&` (ampersand) operatörü ile yapılır.
[source,php]
----
$a = 5;
$b = $a;

// Bu kodlar, $a nın bir kopyasını oluşturur ve bu ayrışık kopyayı $b değişkenine atar.
$a = 7;
// $a = 7 olarak atanırsa acaba, $b değişkeni de 7 mi olur?
// Bu kullanımda $a da gerçekleşen değişimler $b yi etkilemez.
echo '$b : ' . $b;
echo "<br />";


// Bu kodlar, $a nın referansını $b değişkenine aktarır.
$a = 5;
$b = &$a;

$a = 56;
// Bu $b de 56 olur.
echo '$b : ' . $b;
----

=== Karşılaştırma Operatörleri
İki değeri karşılaştırmak için kullanılır. Bu operatörleri kullanan ifadeler, karşılaştırmanın 
sonucunda, mantıksal değerler olan `true` veya `false` değerlerinden birini alır.

|===
|Operatör |Kullanılışı |Eşiti

|`==`
|eşittir
|`$a == $b`

|`===`
|denktir
|`$a === $b`

|`!=`
|eşit değildir
|`$a != $b`

|`<>`
|eşit değildir
|`$a <> $b`

|`<`
|küçüktür
|`$a < $b`
|`>`
|büyüktür
|`$a > $b`

|`pass:[<=]`
|küçük veya eşit
|`$a <= $b`

|`>=`
|büyük veya eşit
|`$a >= $b`
|===

=== Mantıksal Operatörler
Mantıksal operatörler, iki veya daha fazla mantıksal ifadenin sonuçlarını mantıksal olarak birleştirmek için kullanılır.

|===
|Operatör |Adı |Kullanılışı |Sonuç

|`!`
|NOT
|`!$a`
|`$a` `false` is `true`, `true` ise `false` değerini döndürür.

|`&&`
|AND
|`$a && $b`
|`$a` ile `$b` değişkenlerinin ikisi de `true` ise `true`,  aksi durumlarda `false` döndürür.

|`&#124;&#124;`
|OR
|`$a &#124;&#124; $b`
|`$a` ile `$b` değişkenlerinin ikisinden biri veya ikisi birden `true` ise `true`,  aksi durumlarda `false` döndürür.
|===

[source, php]
----
$yas = 15;
/*
Yaşı 0-3 arasında olanlara bebek;
Yaşı 4-18 arasında olanlar çocuk;
Yaşı 19-45 arasında olanlar yetişkin;
*/
if( ($yas >= 0) && ($yas <=3) ) {
    echo "Sen bir bebeksin";
}
elseif(($yas > 3) && ($yas <=18))
{
    echo "Sen bir çocuksun";
}
elseif(($yas > 18) && ($yas <=45))
{
    echo "Sen bir yetişkinsin";
}
----

[source, php]
----
<html>
	<head>

	</head>
	<body>

		<form action="online.php" method="post">
			1. Soru : Açık kaynaklı web programlama dili nedir?
			<br />
			<input type="text" name="soru_bir" />
			<br />
			2. Soru : Web sitesi tasarlamak için kullanılan dil nedir?
			<br />
			<input type="text" name="soru_iki" />
			<br />
			<input type="submit" name="test" value="Sınav Sonucumu Göster" />
		</form>
		<?php
		/*
		 * Sorulan iki sorudan en az birini bilen bir kişinin 
		 * başarılı kabul edildiği bir sınav için veya operatörünün kullanılışı.
		 */
		if(!empty($_POST["test"])) {
			$bir = ($_POST["soru_bir"] == "PHP");
			$iki = ($_POST["soru_iki"] == "HTML");

			if($bir or $iki) {
				echo "Sınavdan geçtiniz.";
			}
			else {
				echo "Sınavdan kaldınız.";
			}
		}
		?>
	</body>
</html>
----

=== Ternary Operatörü
`if-else` yapısının kısa şeklidir. Kullanım biçimi aşağıdaki gibidir +
`koşul ? koşul doğru ise değer : koşul yanlış ise değer`

[source, php]
----
<html>
    <head>
	<title>Zebra Stilli Tablo</title>
    </head>
<body>
<?php
echo "<table border='1'>";
$renk="purple";
for($i=1; $i<=15; $i++) {
	echo "<tr bgcolor=$renk><td>A</td><td>B</td></tr>";
	$renk = $renk == "purple" ? "yellow" : "purple";
}
echo "</table>";
?>
</body>
</html>
----
// 24.10.2017 GBIL201 Dersi Sonu

=== Hata Mesajı İptal Operatörü
PHP'de bir deyimin başına `@` operatörü getirildiğinde, bu deyimin üreteceği olası hata iletileri yok sayılır.

=== Operatör Öncelikleri ve Birleşmeleri
Bir operatör ikiden fazla ifade ile kullanıldığında birleşmenin hangi tarafdan başlayarak gerçekleşeciğini 
operatörün birleşme yönü ile tayin edebiliriz.
|===
|Birleşim Yönü |Operatörler

|sağ
|`!`

|sol
|* / %

|sol
|+ - .

|yönsüz
|< pass:[<=] > >=

|yönsüz
|== != === !== <>

|sol
|&

|sol
|&&

|sol
|`&#124;&#124;`

|sağ
|= += -= *= **= /= .= %=
|===
//25.10.2017 BIL201 Dersi Sonu
=== Değişken Fonksiyonları
Bir değişkenin tipi, içeriği gibi bilgileri öğrenmek veya sorgulamak için kullanılan fonksiyonlardır.
Bir değişkenin türünü öğrenemk için `gettype()` fonksiyonu kullanılır.

[source, php]
----
<?php
$degisken="Merhaba";
echo gettype($degisken); // string yazacaktır.

$degisken1=13;
echo gettype($degisken1); //integer yazacaktır.

$degisken2=1.45;
echo gettype($degisken2); //double yzacaktır.

$degisken3=false;
echo gettype($degisken3); //boolean yzacaktır.
?>
----
Bir değişkenin türünü değiştirmek içi `settype()` fonksiyonu kullanılır. `settype()` fonksiyonu 
iki argüman alır. Birinci argüman; türü değiştirilmek istenen değişken, ikinci argüman ise değişkenin yeni türünü
belirten metindir.
[source, php]
----
<?php
$a=56;
echo '$a değişkeninin türü : ' . gettype($a); // integer
echo "<br />";
settype($a, "double");
echo '$a değişkeninin yeni türü : ' . gettype($a); // double
?>
----
PHP ayrıca tip kontrol fonksiyonları da içerir. Bu fonksiyonlar, bir değişkeni argüman olarak alır ve o değiikenin 
ilgili türden olup olmadığını `true` veya `false`  döndürerek bildirir. Bu fonksiyonlar şunlardır:

* `is_array()`
* `is_double()`, `is_float()`, `is_real()`
* `is_long()`, `is_int()`, `is_integer()`
* `is_string()`
* `is_object()`

=== Değişkenin Durumunu Kontrol Etmek
`isset()` fonksiyonu ile bir değişkenin tanımlanıp tanımlanmadığı denetlenebilir. Değişken tanımlı ise `true`, 
tanımlı değilse `false` döndürür. +
Bir değişkenin tanımlı olup olmadığını `empty()` fonksiyonu ile de denetleyebiliriz. Ayrıca `empty()` fonksiyonu, bir değişkenin içeriğinin 
boş veya sıfır olup olmadığını da sınar.
//31.10.2017 GBil ders sonu

[source, php]
----
var_dump(isset($degisken));
/* Yukarıdaki ifadede; $degisken, isset fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmadığından(= operatörü ile bir değer ataması yok) bu
 * değişken tanımsızdır. Dönen değer false olacaktır.
*/
----

[source, php]
----
<?php
$degisken="Merhaba";
var_dump(isset($degisken));
/* Yukarıdaki ifadede; $degisken, isset fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlandığından(= operatörü ile bir değer ataması var) bu
 * değişken tanımlıdır. Dönen değer true olacaktır.
*/
?>
----

[source, php]
----
<?php
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmadığından(= operatörü ile bir değer ataması var) bu
 * değişken tanımsızdır ve dolayısıyla boş olarak düşünülebilir. empty fonksiyonu
 * boş değerde true döndürdüğü için, dönen değer true olacaktır.
 */
?>
----

[source,php]
----
<?php
$degisken="Merhaba";
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmış ve boş değer almamıştır. empty fonksiyonu, değişken
 * boş olmadığında false döndürdüğü için dönen değer false olacaktır.
 */
?>
----

[source, php]
----
<?php
$degisken="";
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda tanımlanmış ama boş değer almıştır. empty fonksiyonu, değişken
 * boş olduğunda true döndürdüğü için dönen değer true olacaktır.
 */
?>
----

[source, php]
----
<?php
$degisken=0;
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda 0 değerini almıştır. empty fonksiyonu, değişken
 * 0 değerini aldığında true döndürdüğü için dönen değer true olacaktır.
 */
?>
----

[source, php]
----
<?php
$degisken=1;
var_dump(empty($degisken));
/* Yukarıdaki ifadede; $degisken, empty fonksiyonu ile denetlenmeden önceki
 * satırlarda 0 değerini almamıştır. empty fonksiyonu, değişken
 * 0 değerini almadığında false döndürdüğü için dönen değer false olacaktır.
 */
?>
----

[source, php]
----
<?php
if(empty($_POST)) {

}
else {
    if(empty($_POST["yil"])) {
        echo "Araç üretim yılını boş girdiniz.!";
    }
    else {
        $arac_uretim_yili = $_POST["yil"];
        settype($arac_uretim_yili, "integer");
        $arac_yasi = 2017 - $arac_uretim_yili + 1;
        $vergi_miktari = 1000 * (1/$arac_yasi);
        echo $vergi_miktari;

    }
}
?>
----
=== Kontrol Yapıları
==== If Deyimi
`If-else` yapısı, bir koşulun sağlanması ve sağlanmaması durumunda farklı kod bloklarının çalışmasını sağlar.
Kullanım şekli aşağıdaki gibidir.
[source, php]
----
if(koşul) {
	// koşul true ise yapılacaklar
}
else {
	// koşul false ise yapılacaklar
}
----

[source, php]
----
<?php
$yas = 2;
if($yas < 4) {
    echo "Bebek";
}
elseif($yas < 12) {
    echo "Çocuk";
}
elseif($yas < 30) {
    echo "Genç";
}
/* if - elseif yapısındaki koşullardan biri sağlandığında o blok çalıştırılır.
 * Sonraki elseif blokları işletilmez.
 * Yukarıdaki örnekte; 2<4, 2<12 ve 2<30 olup bütün elseif bloklarının koşulu sağlanır ama ilk
 * koşulu sqğlaya elseif bloğu 2<4 olduğu için program Bebek çıktısı üretecektir.
 */
?>
----
//01.11.2017 BIL Ders Sonu
