= Sunucu İşletim sistemi
== Windows Server 2012'yi Edinmek

Windows Server 2012'nin öncelikli amacı işletim sistemini, küçük orta ve büyük 
ölçekli şirketlere göre optimize etmektir.
Windows Server 2012'nin şirketinize ve amacınıza uygun değişik sürümleri mevcuttur.

Windows Server 2012, yalnızca 64-bit mimarisine sahip donanımlarda çalışır.

=== Windows Server 2012'nin Sürümleri
* **Windows Server 2012 Foundation :** Limitli özelliklere sahiptir. Sadece OEM 
bilgisayarlar üzerinde çalışır. Bu sürüm sadece tek bir işlemci destekler. Belirli bir 
fiziksel ortamda, 15 kullanıcıya kadar destek verir. Sanallaştırma  ortamlarına izin vermez.
* **Windows Server 2012 Essential : ** Kısıtlanmış özelliklere sahiptir. Sanallaştırma ortamlarına 
izin vermez, 25 kullanıcıya kadar destekler ve tek bir fiziksel ortamda iki işlemciye destek sağlar. 
* **Windows Server 2012 Standart : ** Bütün özelliklere sahiptir. Tek bir fiziksel ortamda 64 fiziksel 
işlemciye kadar destek verir. Ayrıca iki sanal örneğe izin verir.
* **Windows Server 2012 Datacenter : ** Bütün özellikler sahiptir. Tek bir fiziksel ortamda 64 fiziksel işlemciye
kadar destek verir. Sınırsız sayıda sanal örnek oluşturulabilir.

Windows Server 2012, sanal ortamlar oluşturmak için _**Hyper V**_ adı verilen bir teknoloji kullanır.
_**Hyper-V**_ ile, bir fiziksel bilgisayar üzerinde, fiziksel bilgisayarla eş zamanlı çalışabilen birden fazla 
misafir(sanal) bilgisayarlar oluşturulabilir.

=== Windows Server 2012 Kurulumu
==== Kurulum Seçeneklerini Anlamak
Kuruluma başlamadan önce, hangi sabit diskinize ve bu diskin hangi bölümlerine işletim sisteminizi kuracağınıza karar vermelisiniz.
Dilerseniz disk bölümlendirme işlemini Window Server 2012 kurulum CD'sinde yer alan bölümleme aracı ile yapabilirsiniz. +
Windows Server 2012'nin *temiz kurulum* ve *upgrade* olmak üzere iki kurulum seçeneği vardır.
Windows Server 2012, **Full Server**, **Minimal Server Interface** ve **Server Core** olmak üzere 
üç farklı kurulum yapısına sahiptir.

* **Full Server : **  Full Server, konfigürasyonlar için zengin arayüz uygulamalrı içerenve masaüstü ortamnına 
sahip kurulum yapısıdır.
* **Minimal Server Interface : ** Sunucu araçları için minumum düzeyde grafiksel arayüz içeren uygulamalar bulundurur.
* **Server Core : ** Kullanıcı arayüzleri içermeyen, işlemlerin konsol üzerinden yapıldığı kurulum yapısıdır.

=== Windows Server 2012'nin Kurulumu
Kuruluma başlamak için bilgisayarın açılış birimini CDROM olarak değiştirmemiz gerekir. Bu işlem BIOS veya EFI'nin ilgili ayarında yapılabilir.
BIOS(Basic Input Output System), EFI(Extensible Fımrware Interface) +
BIOS tabanlı bilgisayarlar boot disk bölümü için MBR disk türü kullanırken EFI tabanlı bilgisayarlar GPT disk türü kullanırlar.

==== Bilgisayarı İsimlendirme
Bilgisayarınıza, Ahmet, Mehmet gibi isimler verebilirsiniz. Böyle bir isimlendirme, bilgisayarın üstlendiği görev hakkında hiç bir 
bilgi vermez. Bilgisayar sayısı çoğaldıkça bu tarz isimlendirme karışıklığa yol açacaktır. +
Kullanıcılara yönetimsel anlmada kolaylık sağlamak için bir isimlendirme kuralı kabul etmemiz doğru olacaktır. Örneğin, Muhasasebe birimindeki 
bir sunucu bilgisayara, *MuhasebeSunucu01* ismi verilebilir. Bu tarz bir isimlendir sistematiği, bilgisayarı konumu ve görevi hakkında bize bilgi verecektir.
Bilgisayar isimleri domain içinde eşsiz olmalıdırlar. Bilgisayar isimleri en fazla 64 karakter uzunluğunda olabilirler. 

==== Ağ ve Domain Üyelikleri İçin Özellikler
Kurukum sırasında, aşağıda belirtilen ağ ve domain üyelik bilgilerine karar vermeniz gerekmektedir.

=== Rol ve Özellikleri Kurma
İşletim sistemini kurarak, sunucu işletim sistemi oluşturmak için ilk adımı atmmış olduk. 
Fakat sunucu işletim sistemini kurmak demek bilgisayarınızın artık bir sunucu olarak faaliyet göstermeye 
başladığı anlamına gelmemektedir. Istemcilerde, temel işletim sisteminin ana amacı veriyi işlemek ve tüketmektir.
Sunucu işletim sistemlerinin öncelikli amacı ise veriyi istemcilere sunmaktır. 
Bu sebeple siz sunucuya neyi sunacağı konusunda bir şey bildirmezseniz sunucu amaçsız çalışacaktır. +
Windows Server 2016'da sunucuya, hangi verileri nasıl sunacağı konusunda verdiğiniz görevlere __rol ve özellikler__ denir. +
_Rol_ sözcüğü ile, sunucuya ağ üzerinde biçilen rolün, Windows Server 2016'da yer alan yönetimsel araçlarla kurulması ifade 
edilmektedir. Diğer bir ifadeyle, rolller sunucuya ağ üzerinde var olma amacı verir. +
_Özellikler_ ise sunucunun belirli bir özelliği kazanabilmesi için gerekli olan fonksiyon yığınını ekler.

==== Sihirbazı Kullanarak Bir Rol Yükleme
Hiç şüphe yok ki, rollerin ve özelliklerin yüklü olduğu en yaygın yer, işletim sistemi yüklenir yüklenmez kullanılabilir grafik sihirbazlarının hemen içindedir. Varsayılan olarak, Windows Server 2016'ya her giriş yaptığınızda otomatik olarak Server Manager uygulaması açılacaktır.
Yeni kurduğumuz sunucuya giriş yaptığnızda karşınıza 
Server Manager aracı çıkacaktır. 
Bu aracın içinde, birden beşe kadar numaralandırılmış 
linkler halinde başlangıçta yapılacaklar listesi göreceğiz. 
Öncelikle sunucumuzuni, yerel bir sunucu olarak çalışa
bilmesi için gerekli şartları oluşturmamıza sağlayan 
_Configure this local server_ bağlantısına tıklayacağız.
Bu şartlar, kesin bir bilgisayar ismi belirleme, ip adresini
statik olarak sabitleme gibi adımlardan oluşur.
Bu kısmı geçtikten sonra ikinci adıma geçiyoruz. 
_Add roles and features_ bağlantısına tıklayalım. 
Aynı işlemi, Server Manager penceresinin sağ üst kısmında
yer alan _Manage_ menüsünden _Add roles and features_
seçeneğine tıklayarak da açabiliriz.
Sonradında rol ve özellik eklememize yardımcı olan bir 
sihirbaz bizi karşılayacaktır.
İlk olara, rol kurma hakkında bilgiler içeren yazıların
olduğu bir ekran karşımıza gelecektir. 
_Next_ düğmesine basarak ilerleyelim. Bu pencerede, _Role-based or feature-based installation_ ve _Remote Desktop Services 
installation_ seçeneklerini göreceğiz. Biz burada; _Role-based or feature-based installation_ seçeneğini seçeceğiz. 
_Remote Desktop Services installation_  seçeneği ile devam ederseniz sunucunuza uzak masaüstü erişimi yapabilmek için gerekli 
olan yazılımların kurulumunu yapmış olursunuz. +
Biz, Windows Server 2016'yı denemek için bir test ortamı oluşturacağımızdan dolayı, içinde bulunduğum ortamda 
bulunan _Active Directory_ yapısını yönetecek bir __Domain Controller__'a ihtiyacım olacaktır. Sunucuya _AD DS_ 
rolünü eklemeden önce, sunucumuzda bazı ön koşulları yerine getirmeliyiz. Bu koşullar şunlardır:

* Bilgisayarınızı ismine(hostname) kesin ve değişmeyecek şekilde karar vermiş ve atamış olmanızz.
* IP adresinizi otomatik olarak(DHCP) değil kesin ve değişmeyecek biçimde statik olarak alınmış olması.
* Network ayarlarında DNS bölümüne en azından snunucu bilgisayarın ip adresi olacak şekilde DNS sunucularının girilmiş olması.

Bu işlemleri gerçekleştirdikten sonra _Next_ düğmesine basıp ilerleyelin. Karşımıza rolü hangi sunucuya kurmak istediğimizi 
soran _Server Selection_ penceresi gelecektir. Burada ağınızda bulunan diğer sunucularda listelenecek ve 
yetkiniz yeterliyse bu sunuculardan birini seçerek rolü bu sunucuya kurulacaktır. Her zaman için, üzerinde çalıştığınız sunucu
burada ilk  sırada yer alır ve genellikle onu seçerek ilerleriz. Ayrıca, sunucunuzda `.VHDX` uzantısına sahip olan 
sanal sunucular varsa _Select a virtual hard disk_ seçeneğini seçerek rolünüzü bunlardan birine kurabilirsiniz. 
Kurulum yapacağımız sunucuyu seçtikten sonra karşımıza, kurabileceğimiz tüm rollerin bir listesi çıkacaktır. 
Bir rolün kurulumuna başlamak için, Kuracağımız rolün solunda yer alan seçim kutucuğunu işaretleyip _Next_ düğmesine 
basmamız yeterli olacaktır. Birden fazla rolü kurmak istememiz durumunda, bu işlemleri hepsi için tekrar yapmaya gerek yoktur. 
Dolayısıyla bu aşamada istediğimiz kadar rolün seçim kutucuğunu işaretleyip hepsini tek bir seferde kurabiliriz. 
Bu sunucu bilgisayarı _Domain Controller_ olarak görevlendirmek istediğimizden biz bu burada _Active Directory Domain 
Services_ rolünü seçiyoruz. Seçim yaptıktan sonra bu rolün düzgün çalışması için kurulması gereken özelliklerin bir
listesi karşımıza çıkacaktır. Bir çok rol düzgün çalışabilmesi için ek bileşenlere ve özelliklere ihtiyaç duyar. 
Rolü ve gereksinim duyduğu tüm bu ek özellikleri kurabilmek için _Add Features_ butonuna basmamız yeterli olacaktır. 
Biz burada sunucu bilgisayarımıza ayrıca _DHCP Server_ ve _DNS Server_ rollerini de ekleyeceğimiz için onlara 
ait seçim kutularını da işaretleyip _Add Features_ düğmesinine basıyoruz. Bu hizmetlerin kurulabilmek için birbirine 
bağımlı değildir. Yani her birini farklı sunucu bilgisayarlarda kurabilirsiniz. Genelde büyük ölçekli teşkilatlanmlarda 
bu seçenek tercih edilir. Ama biz küçük bir test ortamı oluşturmak istediğimizden hepsini tek bir sunucuya kuruyoruz. +
Kurulum işlemi tamamlandıktan sonra, bilgisayarı yeniden başlatmak isteyip istemediğinizi soran bir dialog penceresi 
ile karşılaşacaksınız. Bazı roller kurulduklarında bilgisayarınızı yeniden başlatmanız gerekebilir. Server Manager 
penceresini tekrar baktığınınızda, üst kısımda sarı renkli bir ünlem işareti göreceğiz. Bu alana tıkladığımızda, 
rollerin kurulumun tamamlanması ve işler hale gelebilmesi için gerekli olan ayarlar hakkında bilgi veren mesajlar göreceğiz. 
Örneğin sunucumuzun _Domain Controller_ hizmetini vermeye başlaması için etki alanını tanımlayacak olan veya 
katılmak isteyeceğimiz etki alanını bildireceğimiz yükseltme işlemini yapmamız gerekir. 

=== PowerShell Kullanarak Bir Özellik Kurma
Şimdiye kadar grafik arayüzlü sihirbazlar ile rol ve özellik kurulumunu öğrendik. Rol ve özellik kurmak için her zaman 
bu sihirbazları kullanabiliriz. Ayrıca Microsoft,rol ve özellik ekleme de dahil olmak üzere bir çok işlemin yapılabileceeği 
_PowerShell_ adı verilen bir komut satırı istemcisi oluşturdu. PowerShell'de rol ve özellikleri listelemeye ve kurmaya 
yarayan komutlar bir göz atalım. +
Yetkili bir PowerShell komut satırı istemcisini açıp `Get-WindowsFeature` komutunu verelim. Bu komut bize, sunucumuza 
kurabileceğimiz tüm rol ve özelliklerin bir listesini verecektir. Ayrıca hangi rol ve özelliklerin kurulu olduğunu 
bize gösterecektir. +
Örneğin _Telenet Client_ özelliği kurmak istediğimizi düşünelim. Telnet ağ bağlantılarını kontrol etmek için kullanılır ve 
sunucumuz için faydalı olacaktır. Maalesef PowerShell'de verilen `Get-WindowsFeature` komutunun çıktısı sayfalarca ve 
ayrıca _Telnet Client_ özelliğini kurmak için tam olarak neyi arayacağımı bilmiyorum. Şimdi yine `Get-WindowsFeature` 
komutunu vereceğiz ancak komutun çıktısını isteğimize göre filtreleyip azaltmak komutun söz dizimini biraz değiştirerek 
eklemeler yapacağız. Sadece ismi `TEL` ile başlayan özellikleri görebilmek için +
`Get-WindowsFeature -Name TEL*` +
komutunu verelim. Bu komutun çıktısında _Telnet Client_ özelliğini ve ona ait bilgileri net olarak görebiliriz. 
Bir özelliği PowerShell ile eklemek için o özelliğin ismini `Add-WindowsFeature` komutuna argüman olarak vermek yeterli 
olacaktır. O halde,

[source, powershell]
----
Add-WindowsFeature Telnet-Client
----
komutunu verdiğimizde Telnet Clien özelliği sunucu bilgisayara kurulacaktır. +
Sunucumuzda kurulu olan tüm rol ve özellikleri görebilmek için `Get-WindowsFeature | Where Installed` komutunu kullanabilirsiniz.

=== Merkezi Yönetim ve İzleme
Yeni roller kurarken, yedek alırken, programlara bakım yaparken ya da sorun giderirken mantıken üzerinde çalıştığımız 
sunucuya giriş yapmamız gerekecektir. Önceleri bu eylem, ancak sunucu bilgisayarın karşısına geçip 
fare ve klavyeyi kullanmak vasıtasıyla yapılabilirdi. Ancak uzun zamandır bu eylemi yapabilmek için fiziksel olarak sunucu 
bilgisayarın karşısında olmanıza gerek yok. _Remote Desktop Services (RDP)_ teknolojisi bize, sunucularımızı uzak 
bilgisayarlardan yönetme imkanı sağlar. Windows Server 2016 içerdiği bazı araçlar ile __RDP__'ye olan gereksinimi 
azaltmıştır. Bu araçları yakından inceleyelim.

==== Server Manager
Windows Server 2016 kurulu bir bilgisayara her giriş yaptığınızda _Server Manager_ aracı otomatik olarak başlatılır. 
Uygulamanın penceresi incelendiğinde, sunucuda kurulu olan hizmetler hakkında özet bilgiler verdiği görülebilir. 
Sol sütunda sunucuda kurulu olan rollerin bir listesi yer alır. Bu rollerden birine tıkladığınızda rol ile ilgili ayarlar 
ve özelliklere erişebilirsiniz. Çoğu zaman birden fazla sunucuyla çalışmak zorunda kalabilirsiniz. _Server Manager_ 
penceresinin altında yer alan _Roles and Server Groups_ sunucularınızı gruplandırmaya yarar. Bu kısımda aynı zamanda 
sunucularınızda çalışan rolleri görebilirsiniz. Bizim sunucumuzda şimdilik _AD DS_ ve _DHCP_ rollerini eklediğimizden 
bu kısımda onlar listelenecektir. Rollerin isminin yazdığı başlık kısmının arkaplan rengi kırmızı ise ilgili rolün düzgün 
çalışmadığını; yeşil ise rolün sorunsuz çalıştığını anlayacağız. Her iki durumda da rollerin üstüne tıklayarak daha 
fazla bilgi edinebilirsiniz. +
Server Manager penceresinin üst tarafında yer alan menüde bulunan _Tools_ seçeneğine tıkladığınızda, sunucuda 
kullanabileceğiz yönetimsel araçların bir listesini göreceksiniz. 

=== sysprep ile işletim Sisteminin Hazır kalıplarını Oluşturmak
Widows Server 2016'yı kurmak çok da zahmetli değildir. Fakat çok sayıda sunucu bilgisayarınız varsa, benzer rutinleri 
tekrar etmek zor ve sıkıcı olabilir. Birbirine benzer donanıma sahip bilgisayarlara ya da sanal makinelere _sysprep_ 
yardımıyla işletim sistemini zahmetsiz bir şekilde kurabiliriz.
Microsoft System Preparation Tool

=== Active Directory Nedir?
Active Directory Windows Server ağlarındaki bir dizin hizmetidir. Dizin hizmeti, ağdaki kaynakların bilgisini tutan ve bu bilgiyi 
kullanıcılara ve uygulamalara sunan ağ hizmetidir. 
Dizin hizmeti ağ kaynaklarına ulaşmak, bu kaynakları isimlendirmek ve güvenli bir şekilde yönetmek için gereken ortamı sağlamak amacıyla oluşturulur.
Active Directory ortamdaki ağ altyapısına büyük ölçüde işlevsellik kazandırmaktadır. 
Özellikle kaynakların kontrolünün ve yönetiminin merkezileştirilmesi Active Directory organizasyonunun en önemli özelliğidir. 
Active Directory, fiziksel topoloji üzerine dayalı bir sistemin kullanıcıya daha baside indirgenmiş şekilde görünmesini ve kaynaklara
erişim esnasında kullanıcının eriştiği kaynağın (örneğin printer) ağın neresinde olduğunu veya kaynağın ağa ne 
şekilde bağlanmış olduğunu bilmeksizin bağlanmasını sağlar. +
Active Directory kurulu bir Windows Server 2016 ağ çapında sistem konfigürasyonlarını, kullanıcı profillerini ve uygulama bilgilerini Active Directory veritabanında saklar.
Active Directory sistem yöneticilerinin, domain kapsamındaki tüm bilgisayarlarda desktop özelliklerini, ağ servislerini ve uygulamaları
merkezi bir noktadan yönetebilmelerini sağlar. +
Active Directory ayrıca, kullanıcıların sisteme bir kez dahil olmasını, yani logon olmasını ve ardından ağdaki birçok kaynağa tek bir logonla güvenli bir şekilde erişebilmesi konusunda da sistem yöneticilerine merkezi erişim kontrolü sağlar.

==== Domain Controller
Domain Controller, domain yapısını kuran ve domain veritabanının depolandığı bilgisayarlara verilen isimdir. Kısaca DC denir. 

==== Active Directory Objeleri
Active Directory, veritabanında ağ objeleri hakkındaki bilgileri saklar. Bu Active Directory objeleri başta kullanıcılar, gruplar, bilgisayarlar ve yazıcılar olmak üzere ağ kaynaklarını temsil etmektedir. Dahası, Active Directory çapındaki tüm sunucular, Domain’ler ve Site’lar da Active Directory objeleri arasında yer almaktadır. Active Directory tüm objeleri dağıtılmış bir veritabanı üzerinde sakladığı için sistem yönticisi bu objelerin yönetimi kolaylıkla tek bir noktadan yürütebilir.
Yeni bir obje oluşturulduğu zaman bu objenin özellikleri (attribute) obje hakkında onu tanımlayan bilgiler içerir. Kullanıcılar bu objeye erişmek istediği zaman objeye atanan bu özelliklerden faydalanabilirler. Örneğin, bir kullanıcı domain içerisinde bir yazıcıya ulaşıyorken yazıcının bulunduğu yere (kat, bina, departman) göre arama yapabilir.

==== Active Directory’nin Mantıksal Yapısı

Active Directory’nin mantıksal yapısı, esnekliğinin yanısıra Active Directory içerisinde kullanıcı ve yönetici kapsamında hiyerarşik bir yapı kurulmasına olanak verir.
Söz konusu mantıksal komponentler

. Domain
. Organizational unit
. Tree and forest
. Global catalog

===== Domain
Active Directory en temel mantıksal bileşeni Domain’dir. Domain, aynı dizin veritabanını paylaşan bilgisayarlar bütünüdür ve sistem yöneticisi tarafından oluşturulur. Her bir Domain benzersiz bir isme sahiptir ve sistem yöneticisi tarafından belirlenmiş olan kullanıcı ve grup hesaplarına erişim sağlar.
Ayrıca Domain’ler güvenlik sınırı (Security Boundary) olarak da bilinir. Güvenlik sınırı sayesinde, eğer sistem yöneticisi ayrıca bir izin belirlememişse, bir kullanıcının hakları sadece o Domain içerisinde geçerli olacaktır. Her bir Domain kendi güvenlik yapısına sahiptir.
Domain’ler ayrıca replikasyon birimi olarak adlandırılır. Bir Domain içerisinde, Active Directory veritabanı kopyalarını bulunduran Domain Controller’lar bu koyaları Domain içerisinde yapılan değişiklikleri birbirlerine kopyalarak replikasyon yaparlar.

===== Organizational Units
Organizational Unit bir Domain içerisindeki objeleri organize etmek amacıyla oluşturulmuş objelerdir. Bir Organizational Unit kendi içerisinde kullanıcılar, gruplar, bilgisayarlar veya başka OU’lar olmak üzere başka objeler barındırabilirler.
OU’ları, organizasyonun ihtiyacını en iyi şekilde karşılayacak mantıksal bir hiyerarşi oluşturuyorken objeleri gruplamak amacıyla kullanabilirsiniz.
Örneğin, objeleri grupluyorken yönetimsel gereksinimleri ön planda tutabilirsiniz. Mesela, organizasyonda bir yönetici kullanıcılarda bir diğer kullanıcı da bilgisayarlardan sorumlu olacaksa, biri kullanıcılar için biri de bilgisayarlar için iki adet OU oluşturulur ve kullanıcılar birinde bilgisayarlar da diğerin toplanır. Son olarak da ikisini de ilgili kullanıcı yönetici olarak atanabilir.
OU birimlerinin kullanılabileceği bir başka örnek ise organizasyonun departmansal birimlere ayrılmasında geçerli olabilir. Örneğin bir “Muhasebe” bir de “Pazarlama” departmanları için OU oluşturulur ve bu departmanlarda çalışan kullanıcılar ilgili Oulara yerleştirildikten sonra departman şefleri bu birimlere yönetici olarak atanabilir.,

===== Trees ve Forests
Oluşturulan ilk Windows Server 2016 Domain’i, Active Directory yapısındaki Kök Domain’i (Root Domain) ifade eder. Bundan sonra oluşturulacak olan yeni ek Domain’ler dizinin mantıksal Tree veya Forest yapısını oluşturacaktır.

* **Tree** +
Birbirine ardışık bir isim aralığını paylaşan Windows Server 2003 Domain’lerinin hiyerarşik olarak düzenlenmiş şeklidir.Önceden oluşturulmuş bir Tree yapısında yeni bir Domain eklediğiniz zaman, yeni eklenen Domain sondan eklendiği Domain’inin Child Domain’i durumunda olur ve eklendiği Domain de eklenen Domain için Parent Domain olur. Yeni oluşturulan Child Domain’in ismi Parent Domain’den gelen isimle birleştirilir ve yeni oluşan Domain’in DNS ismi ortaya çıkar.
Örneğin bakicubuk.com bir Root Domain’dir. Bu Domain’e eklenecek yeni bir Domain baki.com Domain’inin Child Domain’i olacaktır, buna örnek olarak it.baki.com Domain’ini gösterebiliriz. Bu örnekte it.baki.com, baki.com Domain’inin Child Domain’i olacaktır. baki.com Domain’i ise Parent Domain konumundadır.
* **Forests** : 
Forest, birden fazla Tree’nin birleşmiş halidir. Forest içerisindeki Tree’ler ardışık isim aralığına sahip değildirler. Oluşturulan ilk Domain bir Tree’yi ifade edecektir ve ilk Tree’nin oluşturulmasıyla Forest’da oluşmuş olacaktır. Sonradan bu Forest’a eklenecek olan Tree’ler, diğer Tree’lerle aynı isim aralığını paylaşmayacak olasalar da aynı Schema ve Global Catalog’a sahip olacaktır. Forest oluşturulurken kurulmuş olan ilk Tree Forest-Root olarak bilinir ve diğer Tree’ler bu Forest Root altında toplanırlar.
* **Global Catalog** : 
Global Catalog, Active Directory’deki tüm objelerin özelliklerinin bir alt kümesini taşıyan bilgi deposudur. Bu barındırılan özellikler, varsayılan olarak, sorgulamalar esnasında en sık kullanılan özelliklerdir (örneğin kullanıcı ön ismi, son ismi ve logon ismi). Global Catalog kullanıcılara şu hizmetleri sunar:

** Gereken verinin nerede olduğundan bağımsız olarak Active Directory objeleri hakkında bilgiler sunar.
** Bir ağa logon oluyorken Universal Group Membership bilgisini kullanır.
Global Catalog Sunucusu Domain’deki bir Domain Controller’dır ve Domain’de oluşturulan ilk Domain Controller otomatik olarak Global Catalog seviyesine yükseltilir. Sonradan ek Global Catalog Sunucular eklenebilir.

* ** Active Directory Schema** : Kullanıcı, grup, bilgisayar ve yazıcılar gibi bütün objelere ait bilgileri içerir. 
Windows 2000 ve sonrasında tüm Network yapınız (forest) içerisinde, sadece bir Schema bulunur ve bütün obje bilgileri Schema üzerine yazılır. Schema yapısında, obje sınıfı ve niteliği tanımlanabilir. 
Obje sınıfı: Bilgisayar, kullanıcı veya yazıcı olabilir. Nitelik: Schema içinde bir
kez tanımlandıktan sonra, arama(search) işlemlerinde kullanılabilir.
Örneğin: Kullanıcıların çalıştıkları bölümler, doğum yeri gibi.
Schema bilgileri: Active Directory veri tabanı(database) içerisinde depolanır.
Dolayısı ile
• Kullanıcı uygulamaları için dinamik bir yapı sunar. Kullanıcıların obje araştırma işlemleri, Schema üzerinden gerçekleşir.
• Yeni oluşturulan veya değiştirilen obje dinamik olarak Schema içerisinde
güncellenir.

==== Active Directory’nin Fiziksel Yapısı
Active Directory içinde mantıksal yapı, fiziksel yapıdan bağımsız ve farklı bir yapıya sahiptir. Mantıksal yapı ile Network kaynaklarını organize ederken, fiziksel yapı ile Network trafiğini kontrol ve konfıgüre edebilirsiniz.
Active Directory’nin fiziksel yapısını; DC(Domain Controller) ve Siteler oluşturur. Active Directory’nin fiziksel yapısı, replikasyonun yer ve zamanı ile Network’e katılımını(logon) belirler. Network trafiği ile logon işlemlerinin optimizasyonu ve bu işlemlerde olabilecek hataların giderilmesi, fiziksel yapının anlaşılmasına bağlıdır.

===== Domain Controllers
Domain Controller, üzerinde Active Directory veritabanının bir kopyasını (replica) bulunduran bilgisayardır.Domain’de gerşekleştirilen herhangi bir değişiklik bir Domain Controller üzerinde gerçekleştirilir ve daha sonra domain’deki tüm Domain Controller’lar bu değişiklikleri replikasyon yoluyla birbirlerine kopyalarlar. Domain Controller’lar dizin bilgisini bulundururlar ve kullanıcıların logon işlemlerini, kimlik doğrulama işlemlerini ve dizin arama işlemlerini yürütürler.
Bir Domain’de bir veya daha çok Domain Controller olabilir. Ufak çapta bir organizasyona (LAN) bir Domain ve iki Domain Controller yetecekken farklı fiziksel lokasyonlara yayılmış büyük bir işletme için (WAN), her bir bölge başına bir veya iki Domain Controller daha uygun olacaktır. Bir Domain’e birden fazla Domain Controller yerleştirmenin amacı hem hata toleransı sağlamak hem de Domain Controller’lar arasında yük dağılımı yapmaktır.

===== Sites
Bir Site, birbirlerine yüksek bant genişliğine sahip dış hatlarlar bağlanmış bir veya birden fazla IP (Internet Protocol) alt ağlarını ifade etmektedir. Site’ları doğru bir şekilde yapılandırarak kullanıcıların logon işlemlerinde oluşan ağ trafiğini ve replikasyon işlemleri sırasında oluşan yoğunluğu en aza indirgemek için Active Directory’nin alt ağlar arasındaki fiziksel bağlantıları en efektif şekilde kullanmasını sağlayabiliriz.
Site oluşturmaktaki başlıca sebepler şunlardır:
• Replikasyon trafiğinin optimize edilmesi
• Kullanıcıların logon olması esnasında en hızlı ve en güvenilir bağlantıyı kullanarak doğru Domain Controller’ı bulabilmelerii

==== DNS
DNS, anlamlı alan isimleri ile ip adreslerini birbirine eşlemeye yarayan sistemdir.
