== Web Editörü

=== Var Olan CSS Şablonunu Düzenleme
Var Olan CSS Şablonunu Düzenleme

. File->New menü yolu izlenir.
. Blank Page -> HTML -> HTML5: 2 Column fixed, right sidebar
seçeneği seçilir.
. CSS stil şablonları aktif olmadığında sayfanın nasıl
gözüktüğünü görmek için View -> Style Rendering -> Display Styles
seçeneği üzerindeki tik kaldırılır.

=== Header Bölümüne Arkaplan Resmi Ekleme
. Insert_Logo yer tutucusuna tıklanır ve sonra Del tuşuna
basılır. Bu işlem ile yer tutucu nesnesi silinmiş olur.
. Görünür değilse Styles panelini gösterelim. Bunun için
Window &#9654; CSS Styles menü yolu izlenebilir.
. CSS Styles panelinde header kuralı bulunur ve çift tıklanır.
Karşımıza "CSS Rule Definition for header" dialog pnceresi
gelecektir.
. Bu dialog penceresinin "Background" kategorisi altında bulunan
"background-image" alanındaki Browse butonuna tıklanır.
5 "banner.jpg" seçilir ve Apply, OK buttonları ile devam edilir.
. Arkaplan resmi, header nesnesin daha büyük yüksekliğe
sahip olduğundan resmin sadece bir bölümü gözükmektedir.
Bunu düzeltmek için, header nesnesinin yüksekliğini, resmin
yüksekliğiyle aynı yapmak gerekir. Resmin yüksekliği 130px ol
duğunu düşünelim. header nesnesinin yüksekliğini ayarlamak için
CSS Styles panelinde header kuralına çift tıklarnır.
Rule Definition dialog penceresinin Box kategorisi altından
 height alanı 130px olarak ayarlanır.

=== Yeni Bileşenler Ekleme
. İmleci *header* nesnesi içinde herhangi bir yere konumlandır. Klavyeden 
*Sol Ok* tuşuna basılır.
. *Konumlandırılabilir Kutu* eklemek için, * Insert &#9654 Layout Objects -> AP Div 
menü yolu izlenir.


Web sitesi oluşturmanın temelleri

Bir web sitesi oluşrumaan önce aşağıdaki sorulara cevap vermek gerekir.

1. Web sitesinin amacı nedir?

2. Web sitesinin hedef kitlesi kimlerdir?

3. Ziyaretçiler web sitesini nasıl ziyaret edecekler?



Web Sitesinin Amacı.

Bir e-ticaret veya ürün destek sitesi mi oluşturacağız?

Bir blog veya günlük sitesi mi?

Servis sağlayan bir hizmet sitesi mi?

Ziyaretçiler, web sitesini gezinirken kredi kartına ihitiyaç duyacaklar mı?

Web sitemiz için veritabanına ihtiyaç var mı?

Benzer sorulara cevap verdiğimizde, web sitemizin içeriğinin nasıl olacağını ve web sitesinin oluştururken hangi teknolojileri kullanıcığımız öngürmüş oluruz. 



* Web sitesinin Hedef Kitlesi

Web sitenizi zayeret edecek kullanıcılar bir profil oluşturuyorlar mı?

Örneğin, genellikle çocuklar tarafından ilgi duyulan içeriklere mi sahipsiniz?

Ya da sadece yetişkinlerin anlayabileceği konular mı mevcut?

Veya sadece kadınlara yada erkeklere de hitap eden bir web sayfası mı?

Örneğin sadece belli bir hobisi olan ziyaretçilere mi sahipsiniz?

Örneğin, çocuklara hitap eden bir içeriğie sahipse, sitemizi kolay kullanılabilir, renkli ve animasyonlu olması yararlı olacaktır. 

Benzer tarz siteler mevcutsa, bu sitelerin tasarım ve içerikleri incelenebilir. 

* Nereden gelecekler?

Sitenizi nasıl ziyaret edecekler? Mesela, telefondan, tabletten ya da bilgisayardan mı? 

Ziyaretçilerin ortalama internet hızları ne olacak?

Hangi web tarayıcılarını kullanacakalar?
